[alias]
ta = ["test", "--workspace", "--all-features"]
tn = ["test", "--workspace", "--no-default-features"]
open-doc = [
    "test",
    # "--package",
    # "lang-id",
    "--test",
    "doc",
    "--all-features",
    "--",
    "build_and_open_rust_doc",
    "--exact",
    "--show-output",
    "--ignored",
]
