/// Lookup code by the name of the territory.
///
/// ## Example
///
/// ```
/// let map = lang_id::maps::en_001_territory_name::map();
/// assert_eq!(map.get("Latin America"), Some(&"419"));
/// assert_eq!(map.get("China"), Some(&"CN"));
/// assert_eq!(map.get("United Kingdom"), Some(&"GB"));
/// ```
pub const fn map<'m>() -> super::PhfOrderedMap<'m> {
  super::phf::OrderedMap {
    key: 12913932095322966823,
    disps: &[
      (0, 14),
      (0, 194),
      (0, 29),
      (0, 3),
      (1, 3),
      (0, 0),
      (0, 3),
      (1, 16),
      (0, 30),
      (0, 33),
      (0, 24),
      (0, 22),
      (0, 0),
      (0, 18),
      (0, 66),
      (6, 39),
      (0, 1),
      (0, 53),
      (0, 106),
      (2, 192),
      (0, 68),
      (1, 296),
      (8, 54),
      (0, 10),
      (0, 24),
      (0, 67),
      (0, 185),
      (0, 97),
      (0, 8),
      (0, 275),
      (1, 71),
      (0, 137),
      (0, 309),
      (6, 17),
      (0, 4),
      (2, 115),
      (0, 209),
      (4, 20),
      (7, 35),
      (0, 47),
      (0, 1),
      (8, 2),
      (3, 139),
      (7, 277),
      (0, 5),
      (6, 313),
      (0, 67),
      (0, 228),
      (0, 64),
      (9, 176),
      (1, 0),
      (0, 2),
      (0, 30),
      (0, 5),
      (13, 104),
      (0, 58),
      (20, 232),
      (16, 155),
      (0, 7),
      (0, 0),
      (3, 100),
      (2, 71),
      (1, 291),
    ],
    idxs: &[
      50, 10, 46, 30, 237, 299, 267, 257, 310, 211, 168, 166, 152, 264, 17, 20, 194,
      204, 272, 246, 111, 101, 289, 159, 256, 80, 275, 223, 174, 9, 128, 253, 296,
      103, 106, 98, 112, 122, 312, 241, 240, 37, 127, 178, 115, 142, 228, 300, 190,
      248, 105, 29, 186, 254, 6, 221, 71, 203, 102, 36, 309, 165, 297, 1, 133, 167,
      124, 150, 90, 48, 155, 78, 278, 95, 306, 136, 175, 130, 79, 132, 25, 58, 88,
      44, 87, 33, 251, 282, 260, 137, 42, 154, 304, 217, 213, 277, 164, 41, 227, 53,
      74, 193, 247, 280, 107, 188, 73, 13, 126, 179, 189, 11, 234, 94, 70, 51, 293,
      110, 134, 49, 286, 263, 4, 273, 232, 271, 177, 21, 68, 129, 24, 144, 238, 0,
      28, 5, 146, 86, 199, 222, 145, 22, 76, 233, 161, 16, 225, 77, 54, 197, 291,
      140, 192, 82, 261, 198, 182, 305, 176, 153, 139, 125, 2, 119, 81, 75, 252, 69,
      207, 230, 100, 281, 185, 243, 89, 131, 303, 171, 308, 141, 235, 236, 183, 52,
      201, 276, 231, 92, 148, 147, 259, 123, 45, 279, 160, 172, 18, 109, 85, 269,
      38, 181, 116, 205, 31, 196, 313, 255, 27, 311, 216, 151, 170, 262, 220, 138,
      93, 245, 64, 135, 173, 19, 108, 66, 14, 274, 180, 270, 47, 157, 285, 195, 91,
      212, 61, 96, 214, 8, 210, 143, 298, 156, 219, 40, 26, 292, 266, 249, 15, 149,
      114, 32, 97, 43, 200, 191, 187, 84, 226, 99, 12, 295, 290, 83, 258, 209, 268,
      60, 113, 206, 118, 35, 65, 34, 72, 302, 23, 287, 67, 7, 184, 239, 169, 215,
      294, 242, 208, 224, 57, 55, 62, 250, 307, 63, 163, 117, 59, 284, 39, 121, 104,
      158, 265, 244, 56, 3, 283, 162, 301, 218, 120, 229, 202, 288,
    ],
    entries: &[
      ("Afghanistan", r###"AF"###),
      ("Africa", r###"002"###),
      ("Albania", r###"AL"###),
      ("Algeria", r###"DZ"###),
      ("American Samoa", r###"AS"###),
      ("Americas", r###"019"###),
      ("Andorra", r###"AD"###),
      ("Angola", r###"AO"###),
      ("Anguilla", r###"AI"###),
      ("Antarctica", r###"AQ"###),
      ("Antigua & Barbuda", r###"AG"###),
      ("Aotearoa New Zealand", r###"NZ-alt-variant"###),
      ("Argentina", r###"AR"###),
      ("Armenia", r###"AM"###),
      ("Aruba", r###"AW"###),
      ("Ascension Island", r###"AC"###),
      ("Asia", r###"142"###),
      ("Australasia", r###"053"###),
      ("Australia", r###"AU"###),
      ("Austria", r###"AT"###),
      ("Azerbaijan", r###"AZ"###),
      ("Bahamas", r###"BS"###),
      ("Bahrain", r###"BH"###),
      ("Bangladesh", r###"BD"###),
      ("Barbados", r###"BB"###),
      ("Belarus", r###"BY"###),
      ("Belgium", r###"BE"###),
      ("Belize", r###"BZ"###),
      ("Benin", r###"BJ"###),
      ("Bermuda", r###"BM"###),
      ("Bhutan", r###"BT"###),
      ("Bolivia", r###"BO"###),
      ("Bosnia", r###"BA-alt-short"###),
      ("Bosnia & Herzegovina", r###"BA"###),
      ("Botswana", r###"BW"###),
      ("Bouvet Island", r###"BV"###),
      ("Brazil", r###"BR"###),
      ("British Indian Ocean Territory", r###"IO"###),
      ("British Virgin Islands", r###"VG"###),
      ("Brunei", r###"BN"###),
      ("Bulgaria", r###"BG"###),
      ("Burkina Faso", r###"BF"###),
      ("Burundi", r###"BI"###),
      ("Cabo Verde", r###"CV-alt-variant"###),
      ("Cambodia", r###"KH"###),
      ("Cameroon", r###"CM"###),
      ("Canada", r###"CA"###),
      ("Canary Islands", r###"IC"###),
      ("Cape Verde", r###"CV"###),
      ("Caribbean", r###"029"###),
      ("Caribbean Netherlands", r###"BQ"###),
      ("Cayman Islands", r###"KY"###),
      ("Central African Republic", r###"CF"###),
      ("Central America", r###"013"###),
      ("Central Asia", r###"143"###),
      ("Ceuta & Melilla", r###"EA"###),
      ("Chad", r###"TD"###),
      ("Chagos Archipelago", r###"IO-alt-chagos"###),
      ("Chile", r###"CL"###),
      ("China", r###"CN"###),
      ("Christmas Island", r###"CX"###),
      ("Clipperton Island", r###"CP"###),
      ("Cocos (Keeling) Islands", r###"CC"###),
      ("Colombia", r###"CO"###),
      ("Comoros", r###"KM"###),
      ("Congo (DRC)", r###"CD-alt-variant"###),
      ("Congo (Republic)", r###"CG-alt-variant"###),
      ("Congo - Brazzaville", r###"CG"###),
      ("Congo - Kinshasa", r###"CD"###),
      ("Cook Islands", r###"CK"###),
      ("Costa Rica", r###"CR"###),
      ("Croatia", r###"HR"###),
      ("Cuba", r###"CU"###),
      ("Curaçao", r###"CW"###),
      ("Cyprus", r###"CY"###),
      ("Czech Republic", r###"CZ-alt-variant"###),
      ("Czechia", r###"CZ"###),
      ("Côte d’Ivoire", r###"CI"###),
      ("Denmark", r###"DK"###),
      ("Diego Garcia", r###"DG"###),
      ("Djibouti", r###"DJ"###),
      ("Dominica", r###"DM"###),
      ("Dominican Republic", r###"DO"###),
      ("East Timor", r###"TL-alt-variant"###),
      ("Eastern Africa", r###"014"###),
      ("Eastern Asia", r###"030"###),
      ("Eastern Europe", r###"151"###),
      ("Ecuador", r###"EC"###),
      ("Egypt", r###"EG"###),
      ("El Salvador", r###"SV"###),
      ("Equatorial Guinea", r###"GQ"###),
      ("Eritrea", r###"ER"###),
      ("Estonia", r###"EE"###),
      ("Eswatini", r###"SZ"###),
      ("Ethiopia", r###"ET"###),
      ("Europe", r###"150"###),
      ("European Union", r###"EU"###),
      ("Eurozone", r###"EZ"###),
      ("Falkland Islands", r###"FK"###),
      ("Falkland Islands (Islas Malvinas)", r###"FK-alt-variant"###),
      ("Faroe Islands", r###"FO"###),
      ("Fiji", r###"FJ"###),
      ("Finland", r###"FI"###),
      ("France", r###"FR"###),
      ("French Guiana", r###"GF"###),
      ("French Polynesia", r###"PF"###),
      ("French Southern Territories", r###"TF"###),
      ("Gabon", r###"GA"###),
      ("Gambia", r###"GM"###),
      ("Georgia", r###"GE"###),
      ("Germany", r###"DE"###),
      ("Ghana", r###"GH"###),
      ("Gibraltar", r###"GI"###),
      ("Greece", r###"GR"###),
      ("Greenland", r###"GL"###),
      ("Grenada", r###"GD"###),
      ("Guadeloupe", r###"GP"###),
      ("Guam", r###"GU"###),
      ("Guatemala", r###"GT"###),
      ("Guernsey", r###"GG"###),
      ("Guinea", r###"GN"###),
      ("Guinea-Bissau", r###"GW"###),
      ("Guyana", r###"GY"###),
      ("Haiti", r###"HT"###),
      ("Heard & McDonald Islands", r###"HM"###),
      ("Honduras", r###"HN"###),
      ("Hong Kong", r###"HK-alt-short"###),
      ("Hong Kong SAR China", r###"HK"###),
      ("Hungary", r###"HU"###),
      ("Iceland", r###"IS"###),
      ("India", r###"IN"###),
      ("Indonesia", r###"ID"###),
      ("Iran", r###"IR"###),
      ("Iraq", r###"IQ"###),
      ("Ireland", r###"IE"###),
      ("Isle of Man", r###"IM"###),
      ("Israel", r###"IL"###),
      ("Italy", r###"IT"###),
      ("Ivory Coast", r###"CI-alt-variant"###),
      ("Jamaica", r###"JM"###),
      ("Japan", r###"JP"###),
      ("Jersey", r###"JE"###),
      ("Jordan", r###"JO"###),
      ("Kazakhstan", r###"KZ"###),
      ("Kenya", r###"KE"###),
      ("Kiribati", r###"KI"###),
      ("Kosovo", r###"XK"###),
      ("Kuwait", r###"KW"###),
      ("Kyrgyzstan", r###"KG"###),
      ("Laos", r###"LA"###),
      ("Latin America", r###"419"###),
      ("Latvia", r###"LV"###),
      ("Lebanon", r###"LB"###),
      ("Lesotho", r###"LS"###),
      ("Liberia", r###"LR"###),
      ("Libya", r###"LY"###),
      ("Liechtenstein", r###"LI"###),
      ("Lithuania", r###"LT"###),
      ("Luxembourg", r###"LU"###),
      ("Macao", r###"MO-alt-short"###),
      ("Macao SAR China", r###"MO"###),
      ("Madagascar", r###"MG"###),
      ("Malawi", r###"MW"###),
      ("Malaysia", r###"MY"###),
      ("Maldives", r###"MV"###),
      ("Mali", r###"ML"###),
      ("Malta", r###"MT"###),
      ("Marshall Islands", r###"MH"###),
      ("Martinique", r###"MQ"###),
      ("Mauritania", r###"MR"###),
      ("Mauritius", r###"MU"###),
      ("Mayotte", r###"YT"###),
      ("Melanesia", r###"054"###),
      ("Mexico", r###"MX"###),
      ("Micronesia", r###"FM"###),
      ("Micronesian Region", r###"057"###),
      ("Middle Africa", r###"017"###),
      ("Moldova", r###"MD"###),
      ("Monaco", r###"MC"###),
      ("Mongolia", r###"MN"###),
      ("Montenegro", r###"ME"###),
      ("Montserrat", r###"MS"###),
      ("Morocco", r###"MA"###),
      ("Mozambique", r###"MZ"###),
      ("Myanmar", r###"MM-alt-short"###),
      ("Myanmar (Burma)", r###"MM"###),
      ("Namibia", r###"NA"###),
      ("Nauru", r###"NR"###),
      ("Nepal", r###"NP"###),
      ("Netherlands", r###"NL"###),
      ("New Caledonia", r###"NC"###),
      ("New Zealand", r###"NZ"###),
      ("Nicaragua", r###"NI"###),
      ("Niger", r###"NE"###),
      ("Nigeria", r###"NG"###),
      ("Niue", r###"NU"###),
      ("Norfolk Island", r###"NF"###),
      ("North America", r###"003"###),
      ("North Korea", r###"KP"###),
      ("North Macedonia", r###"MK"###),
      ("Northern Africa", r###"015"###),
      ("Northern America", r###"021"###),
      ("Northern Europe", r###"154"###),
      ("Northern Mariana Islands", r###"MP"###),
      ("Norway", r###"NO"###),
      ("Oceania", r###"009"###),
      ("Oman", r###"OM"###),
      ("Outlying Oceania", r###"QO"###),
      ("Pakistan", r###"PK"###),
      ("Palau", r###"PW"###),
      ("Palestine", r###"PS-alt-short"###),
      ("Palestinian Territories", r###"PS"###),
      ("Panama", r###"PA"###),
      ("Papua New Guinea", r###"PG"###),
      ("Paraguay", r###"PY"###),
      ("Peru", r###"PE"###),
      ("Philippines", r###"PH"###),
      ("Pitcairn Islands", r###"PN"###),
      ("Poland", r###"PL"###),
      ("Polynesia", r###"061"###),
      ("Portugal", r###"PT"###),
      ("Pseudo-Accents", r###"XA"###),
      ("Pseudo-Bidi", r###"XB"###),
      ("Puerto Rico", r###"PR"###),
      ("Qatar", r###"QA"###),
      ("Romania", r###"RO"###),
      ("Russia", r###"RU"###),
      ("Rwanda", r###"RW"###),
      ("Réunion", r###"RE"###),
      ("Samoa", r###"WS"###),
      ("San Marino", r###"SM"###),
      ("Sark", r###"CQ"###),
      ("Saudi Arabia", r###"SA"###),
      ("Senegal", r###"SN"###),
      ("Serbia", r###"RS"###),
      ("Seychelles", r###"SC"###),
      ("Sierra Leone", r###"SL"###),
      ("Singapore", r###"SG"###),
      ("Sint Maarten", r###"SX"###),
      ("Slovakia", r###"SK"###),
      ("Slovenia", r###"SI"###),
      ("Solomon Islands", r###"SB"###),
      ("Somalia", r###"SO"###),
      ("South Africa", r###"ZA"###),
      ("South America", r###"005"###),
      ("South Georgia & South Sandwich Islands", r###"GS"###),
      ("South Korea", r###"KR"###),
      ("South Sudan", r###"SS"###),
      ("Southeast Asia", r###"035"###),
      ("Southern Africa", r###"018"###),
      ("Southern Asia", r###"034"###),
      ("Southern Europe", r###"039"###),
      ("Spain", r###"ES"###),
      ("Sri Lanka", r###"LK"###),
      ("St Barthélemy", r###"BL"###),
      ("St Helena", r###"SH"###),
      ("St Kitts & Nevis", r###"KN"###),
      ("St Lucia", r###"LC"###),
      ("St Martin", r###"MF"###),
      ("St Pierre & Miquelon", r###"PM"###),
      ("St Vincent & the Grenadines", r###"VC"###),
      ("Sub-Saharan Africa", r###"202"###),
      ("Sudan", r###"SD"###),
      ("Suriname", r###"SR"###),
      ("Svalbard & Jan Mayen", r###"SJ"###),
      ("Swaziland", r###"SZ-alt-variant"###),
      ("Sweden", r###"SE"###),
      ("Switzerland", r###"CH"###),
      ("Syria", r###"SY"###),
      ("São Tomé & Príncipe", r###"ST"###),
      ("Taiwan", r###"TW"###),
      ("Tajikistan", r###"TJ"###),
      ("Tanzania", r###"TZ"###),
      ("Thailand", r###"TH"###),
      ("Timor-Leste", r###"TL"###),
      ("Togo", r###"TG"###),
      ("Tokelau", r###"TK"###),
      ("Tonga", r###"TO"###),
      ("Trinidad & Tobago", r###"TT"###),
      ("Tristan da Cunha", r###"TA"###),
      ("Tunisia", r###"TN"###),
      ("Turkey", r###"TR-alt-variant"###),
      ("Turkmenistan", r###"TM"###),
      ("Turks & Caicos Islands", r###"TC"###),
      ("Tuvalu", r###"TV"###),
      ("Türkiye", r###"TR"###),
      ("UK", r###"GB-alt-short"###),
      ("UN", r###"UN-alt-short"###),
      ("US", r###"US-alt-short"###),
      ("US Outlying Islands", r###"UM"###),
      ("US Virgin Islands", r###"VI"###),
      ("Uganda", r###"UG"###),
      ("Ukraine", r###"UA"###),
      ("United Arab Emirates", r###"AE"###),
      ("United Kingdom", r###"GB"###),
      ("United Nations", r###"UN"###),
      ("United States", r###"US"###),
      ("Unknown Region", r###"ZZ"###),
      ("Uruguay", r###"UY"###),
      ("Uzbekistan", r###"UZ"###),
      ("Vanuatu", r###"VU"###),
      ("Vatican City", r###"VA"###),
      ("Venezuela", r###"VE"###),
      ("Vietnam", r###"VN"###),
      ("Wallis & Futuna", r###"WF"###),
      ("Western Africa", r###"011"###),
      ("Western Asia", r###"145"###),
      ("Western Europe", r###"155"###),
      ("Western Sahara", r###"EH"###),
      ("Yemen", r###"YE"###),
      ("Zambia", r###"ZM"###),
      ("Zimbabwe", r###"ZW"###),
      ("world", r###"001"###),
      ("Åland Islands", r###"AX"###),
    ],
  }
}
