/// Lookup name by the code of the territory.
///
/// ## Example
///
/// ```
/// let map = lang_id::maps::en_001_territory_ids::map();
/// assert_eq!(map.get("419"), Some(&"Latin America"));
/// assert_eq!(map.get("CN"), Some(&"China"));
/// assert_eq!(map.get("GB"), Some(&"United Kingdom"));
/// ```
pub const fn map<'m>() -> super::PhfOrderedMap<'m> {
  super::phf::OrderedMap {
    key: 15467950696543387533,
    disps: &[
      (0, 1),
      (0, 104),
      (0, 19),
      (0, 112),
      (0, 131),
      (0, 0),
      (0, 151),
      (0, 21),
      (0, 50),
      (0, 2),
      (0, 36),
      (1, 1),
      (0, 46),
      (0, 286),
      (0, 14),
      (1, 64),
      (1, 161),
      (0, 9),
      (1, 56),
      (1, 158),
      (1, 173),
      (0, 5),
      (0, 3),
      (0, 67),
      (0, 6),
      (0, 2),
      (0, 66),
      (0, 154),
      (1, 224),
      (0, 3),
      (0, 19),
      (0, 0),
      (2, 94),
      (1, 229),
      (0, 142),
      (1, 15),
      (1, 3),
      (2, 17),
      (2, 70),
      (2, 81),
      (0, 45),
      (2, 5),
      (0, 1),
      (1, 51),
      (0, 237),
      (0, 0),
      (4, 268),
      (0, 120),
      (1, 297),
      (0, 0),
      (0, 238),
      (0, 103),
      (12, 30),
      (0, 5),
      (2, 252),
      (13, 25),
      (0, 191),
      (1, 28),
      (26, 110),
      (0, 29),
      (84, 76),
      (0, 102),
      (5, 149),
    ],
    idxs: &[
      266, 3, 229, 20, 41, 188, 225, 190, 48, 263, 245, 128, 126, 64, 6, 19, 101,
      197, 34, 27, 11, 310, 297, 147, 116, 207, 226, 93, 220, 44, 51, 205, 163, 100,
      117, 33, 7, 170, 139, 12, 227, 135, 134, 57, 276, 198, 122, 279, 146, 120,
      107, 130, 171, 31, 295, 110, 131, 214, 76, 236, 21, 258, 68, 144, 306, 67, 73,
      65, 195, 13, 238, 26, 152, 281, 0, 1, 75, 23, 216, 87, 91, 257, 143, 155, 86,
      288, 84, 119, 223, 234, 264, 273, 262, 213, 259, 208, 292, 105, 286, 221, 106,
      129, 103, 267, 180, 296, 24, 164, 309, 63, 136, 289, 5, 112, 194, 88, 287,
      283, 133, 311, 2, 217, 49, 304, 17, 25, 219, 231, 111, 271, 35, 249, 14, 175,
      149, 181, 308, 60, 203, 80, 154, 169, 243, 312, 161, 177, 202, 121, 8, 72, 61,
      40, 99, 90, 32, 29, 96, 145, 291, 224, 272, 38, 142, 114, 265, 293, 248, 196,
      36, 118, 285, 199, 211, 237, 45, 46, 66, 167, 300, 186, 269, 210, 124, 108,
      50, 241, 158, 313, 305, 307, 104, 92, 157, 168, 74, 56, 302, 4, 58, 62, 125,
      102, 250, 274, 159, 185, 70, 37, 43, 284, 55, 95, 260, 89, 98, 173, 140, 222,
      254, 282, 9, 113, 244, 212, 253, 218, 137, 246, 123, 232, 192, 71, 261, 69,
      178, 79, 280, 184, 209, 230, 183, 215, 255, 182, 239, 153, 174, 193, 109, 252,
      233, 39, 179, 10, 85, 191, 16, 247, 15, 268, 94, 251, 172, 156, 165, 59, 81,
      127, 141, 47, 176, 77, 294, 115, 301, 278, 201, 242, 18, 162, 235, 228, 28,
      83, 314, 30, 22, 166, 97, 275, 240, 189, 151, 200, 150, 52, 160, 138, 206,
      148, 78, 54, 132, 270, 290, 303, 256, 82, 53, 187, 298, 204, 299, 277, 42,
    ],
    entries: &[
      ("001", r###"world"###),
      ("002", r###"Africa"###),
      ("003", r###"North America"###),
      ("005", r###"South America"###),
      ("009", r###"Oceania"###),
      ("011", r###"Western Africa"###),
      ("013", r###"Central America"###),
      ("014", r###"Eastern Africa"###),
      ("015", r###"Northern Africa"###),
      ("017", r###"Middle Africa"###),
      ("018", r###"Southern Africa"###),
      ("019", r###"Americas"###),
      ("021", r###"Northern America"###),
      ("029", r###"Caribbean"###),
      ("030", r###"Eastern Asia"###),
      ("034", r###"Southern Asia"###),
      ("035", r###"Southeast Asia"###),
      ("039", r###"Southern Europe"###),
      ("053", r###"Australasia"###),
      ("054", r###"Melanesia"###),
      ("057", r###"Micronesian Region"###),
      ("061", r###"Polynesia"###),
      ("142", r###"Asia"###),
      ("143", r###"Central Asia"###),
      ("145", r###"Western Asia"###),
      ("150", r###"Europe"###),
      ("151", r###"Eastern Europe"###),
      ("154", r###"Northern Europe"###),
      ("155", r###"Western Europe"###),
      ("202", r###"Sub-Saharan Africa"###),
      ("419", r###"Latin America"###),
      ("AC", r###"Ascension Island"###),
      ("AD", r###"Andorra"###),
      ("AE", r###"United Arab Emirates"###),
      ("AF", r###"Afghanistan"###),
      ("AG", r###"Antigua & Barbuda"###),
      ("AI", r###"Anguilla"###),
      ("AL", r###"Albania"###),
      ("AM", r###"Armenia"###),
      ("AO", r###"Angola"###),
      ("AQ", r###"Antarctica"###),
      ("AR", r###"Argentina"###),
      ("AS", r###"American Samoa"###),
      ("AT", r###"Austria"###),
      ("AU", r###"Australia"###),
      ("AW", r###"Aruba"###),
      ("AX", r###"Åland Islands"###),
      ("AZ", r###"Azerbaijan"###),
      ("BA", r###"Bosnia & Herzegovina"###),
      ("BA-alt-short", r###"Bosnia"###),
      ("BB", r###"Barbados"###),
      ("BD", r###"Bangladesh"###),
      ("BE", r###"Belgium"###),
      ("BF", r###"Burkina Faso"###),
      ("BG", r###"Bulgaria"###),
      ("BH", r###"Bahrain"###),
      ("BI", r###"Burundi"###),
      ("BJ", r###"Benin"###),
      ("BL", r###"St Barthélemy"###),
      ("BM", r###"Bermuda"###),
      ("BN", r###"Brunei"###),
      ("BO", r###"Bolivia"###),
      ("BQ", r###"Caribbean Netherlands"###),
      ("BR", r###"Brazil"###),
      ("BS", r###"Bahamas"###),
      ("BT", r###"Bhutan"###),
      ("BV", r###"Bouvet Island"###),
      ("BW", r###"Botswana"###),
      ("BY", r###"Belarus"###),
      ("BZ", r###"Belize"###),
      ("CA", r###"Canada"###),
      ("CC", r###"Cocos (Keeling) Islands"###),
      ("CD", r###"Congo - Kinshasa"###),
      ("CD-alt-variant", r###"Congo (DRC)"###),
      ("CF", r###"Central African Republic"###),
      ("CG", r###"Congo - Brazzaville"###),
      ("CG-alt-variant", r###"Congo (Republic)"###),
      ("CH", r###"Switzerland"###),
      ("CI", r###"Côte d’Ivoire"###),
      ("CI-alt-variant", r###"Ivory Coast"###),
      ("CK", r###"Cook Islands"###),
      ("CL", r###"Chile"###),
      ("CM", r###"Cameroon"###),
      ("CN", r###"China"###),
      ("CO", r###"Colombia"###),
      ("CP", r###"Clipperton Island"###),
      ("CQ", r###"Sark"###),
      ("CR", r###"Costa Rica"###),
      ("CU", r###"Cuba"###),
      ("CV", r###"Cape Verde"###),
      ("CV-alt-variant", r###"Cabo Verde"###),
      ("CW", r###"Curaçao"###),
      ("CX", r###"Christmas Island"###),
      ("CY", r###"Cyprus"###),
      ("CZ", r###"Czechia"###),
      ("CZ-alt-variant", r###"Czech Republic"###),
      ("DE", r###"Germany"###),
      ("DG", r###"Diego Garcia"###),
      ("DJ", r###"Djibouti"###),
      ("DK", r###"Denmark"###),
      ("DM", r###"Dominica"###),
      ("DO", r###"Dominican Republic"###),
      ("DZ", r###"Algeria"###),
      ("EA", r###"Ceuta & Melilla"###),
      ("EC", r###"Ecuador"###),
      ("EE", r###"Estonia"###),
      ("EG", r###"Egypt"###),
      ("EH", r###"Western Sahara"###),
      ("ER", r###"Eritrea"###),
      ("ES", r###"Spain"###),
      ("ET", r###"Ethiopia"###),
      ("EU", r###"European Union"###),
      ("EZ", r###"Eurozone"###),
      ("FI", r###"Finland"###),
      ("FJ", r###"Fiji"###),
      ("FK", r###"Falkland Islands"###),
      ("FK-alt-variant", r###"Falkland Islands (Islas Malvinas)"###),
      ("FM", r###"Micronesia"###),
      ("FO", r###"Faroe Islands"###),
      ("FR", r###"France"###),
      ("GA", r###"Gabon"###),
      ("GB", r###"United Kingdom"###),
      ("GB-alt-short", r###"UK"###),
      ("GD", r###"Grenada"###),
      ("GE", r###"Georgia"###),
      ("GF", r###"French Guiana"###),
      ("GG", r###"Guernsey"###),
      ("GH", r###"Ghana"###),
      ("GI", r###"Gibraltar"###),
      ("GL", r###"Greenland"###),
      ("GM", r###"Gambia"###),
      ("GN", r###"Guinea"###),
      ("GP", r###"Guadeloupe"###),
      ("GQ", r###"Equatorial Guinea"###),
      ("GR", r###"Greece"###),
      ("GS", r###"South Georgia & South Sandwich Islands"###),
      ("GT", r###"Guatemala"###),
      ("GU", r###"Guam"###),
      ("GW", r###"Guinea-Bissau"###),
      ("GY", r###"Guyana"###),
      ("HK", r###"Hong Kong SAR China"###),
      ("HK-alt-short", r###"Hong Kong"###),
      ("HM", r###"Heard & McDonald Islands"###),
      ("HN", r###"Honduras"###),
      ("HR", r###"Croatia"###),
      ("HT", r###"Haiti"###),
      ("HU", r###"Hungary"###),
      ("IC", r###"Canary Islands"###),
      ("ID", r###"Indonesia"###),
      ("IE", r###"Ireland"###),
      ("IL", r###"Israel"###),
      ("IM", r###"Isle of Man"###),
      ("IN", r###"India"###),
      ("IO", r###"British Indian Ocean Territory"###),
      ("IO-alt-biot", r###"British Indian Ocean Territory"###),
      ("IO-alt-chagos", r###"Chagos Archipelago"###),
      ("IQ", r###"Iraq"###),
      ("IR", r###"Iran"###),
      ("IS", r###"Iceland"###),
      ("IT", r###"Italy"###),
      ("JE", r###"Jersey"###),
      ("JM", r###"Jamaica"###),
      ("JO", r###"Jordan"###),
      ("JP", r###"Japan"###),
      ("KE", r###"Kenya"###),
      ("KG", r###"Kyrgyzstan"###),
      ("KH", r###"Cambodia"###),
      ("KI", r###"Kiribati"###),
      ("KM", r###"Comoros"###),
      ("KN", r###"St Kitts & Nevis"###),
      ("KP", r###"North Korea"###),
      ("KR", r###"South Korea"###),
      ("KW", r###"Kuwait"###),
      ("KY", r###"Cayman Islands"###),
      ("KZ", r###"Kazakhstan"###),
      ("LA", r###"Laos"###),
      ("LB", r###"Lebanon"###),
      ("LC", r###"St Lucia"###),
      ("LI", r###"Liechtenstein"###),
      ("LK", r###"Sri Lanka"###),
      ("LR", r###"Liberia"###),
      ("LS", r###"Lesotho"###),
      ("LT", r###"Lithuania"###),
      ("LU", r###"Luxembourg"###),
      ("LV", r###"Latvia"###),
      ("LY", r###"Libya"###),
      ("MA", r###"Morocco"###),
      ("MC", r###"Monaco"###),
      ("MD", r###"Moldova"###),
      ("ME", r###"Montenegro"###),
      ("MF", r###"St Martin"###),
      ("MG", r###"Madagascar"###),
      ("MH", r###"Marshall Islands"###),
      ("MK", r###"North Macedonia"###),
      ("ML", r###"Mali"###),
      ("MM", r###"Myanmar (Burma)"###),
      ("MM-alt-short", r###"Myanmar"###),
      ("MN", r###"Mongolia"###),
      ("MO", r###"Macao SAR China"###),
      ("MO-alt-short", r###"Macao"###),
      ("MP", r###"Northern Mariana Islands"###),
      ("MQ", r###"Martinique"###),
      ("MR", r###"Mauritania"###),
      ("MS", r###"Montserrat"###),
      ("MT", r###"Malta"###),
      ("MU", r###"Mauritius"###),
      ("MV", r###"Maldives"###),
      ("MW", r###"Malawi"###),
      ("MX", r###"Mexico"###),
      ("MY", r###"Malaysia"###),
      ("MZ", r###"Mozambique"###),
      ("NA", r###"Namibia"###),
      ("NC", r###"New Caledonia"###),
      ("NE", r###"Niger"###),
      ("NF", r###"Norfolk Island"###),
      ("NG", r###"Nigeria"###),
      ("NI", r###"Nicaragua"###),
      ("NL", r###"Netherlands"###),
      ("NO", r###"Norway"###),
      ("NP", r###"Nepal"###),
      ("NR", r###"Nauru"###),
      ("NU", r###"Niue"###),
      ("NZ", r###"New Zealand"###),
      ("NZ-alt-variant", r###"Aotearoa New Zealand"###),
      ("OM", r###"Oman"###),
      ("PA", r###"Panama"###),
      ("PE", r###"Peru"###),
      ("PF", r###"French Polynesia"###),
      ("PG", r###"Papua New Guinea"###),
      ("PH", r###"Philippines"###),
      ("PK", r###"Pakistan"###),
      ("PL", r###"Poland"###),
      ("PM", r###"St Pierre & Miquelon"###),
      ("PN", r###"Pitcairn Islands"###),
      ("PR", r###"Puerto Rico"###),
      ("PS", r###"Palestinian Territories"###),
      ("PS-alt-short", r###"Palestine"###),
      ("PT", r###"Portugal"###),
      ("PW", r###"Palau"###),
      ("PY", r###"Paraguay"###),
      ("QA", r###"Qatar"###),
      ("QO", r###"Outlying Oceania"###),
      ("RE", r###"Réunion"###),
      ("RO", r###"Romania"###),
      ("RS", r###"Serbia"###),
      ("RU", r###"Russia"###),
      ("RW", r###"Rwanda"###),
      ("SA", r###"Saudi Arabia"###),
      ("SB", r###"Solomon Islands"###),
      ("SC", r###"Seychelles"###),
      ("SD", r###"Sudan"###),
      ("SE", r###"Sweden"###),
      ("SG", r###"Singapore"###),
      ("SH", r###"St Helena"###),
      ("SI", r###"Slovenia"###),
      ("SJ", r###"Svalbard & Jan Mayen"###),
      ("SK", r###"Slovakia"###),
      ("SL", r###"Sierra Leone"###),
      ("SM", r###"San Marino"###),
      ("SN", r###"Senegal"###),
      ("SO", r###"Somalia"###),
      ("SR", r###"Suriname"###),
      ("SS", r###"South Sudan"###),
      ("ST", r###"São Tomé & Príncipe"###),
      ("SV", r###"El Salvador"###),
      ("SX", r###"Sint Maarten"###),
      ("SY", r###"Syria"###),
      ("SZ", r###"Eswatini"###),
      ("SZ-alt-variant", r###"Swaziland"###),
      ("TA", r###"Tristan da Cunha"###),
      ("TC", r###"Turks & Caicos Islands"###),
      ("TD", r###"Chad"###),
      ("TF", r###"French Southern Territories"###),
      ("TG", r###"Togo"###),
      ("TH", r###"Thailand"###),
      ("TJ", r###"Tajikistan"###),
      ("TK", r###"Tokelau"###),
      ("TL", r###"Timor-Leste"###),
      ("TL-alt-variant", r###"East Timor"###),
      ("TM", r###"Turkmenistan"###),
      ("TN", r###"Tunisia"###),
      ("TO", r###"Tonga"###),
      ("TR", r###"Türkiye"###),
      ("TR-alt-variant", r###"Turkey"###),
      ("TT", r###"Trinidad & Tobago"###),
      ("TV", r###"Tuvalu"###),
      ("TW", r###"Taiwan"###),
      ("TZ", r###"Tanzania"###),
      ("UA", r###"Ukraine"###),
      ("UG", r###"Uganda"###),
      ("UM", r###"US Outlying Islands"###),
      ("UN", r###"United Nations"###),
      ("UN-alt-short", r###"UN"###),
      ("US", r###"United States"###),
      ("US-alt-short", r###"US"###),
      ("UY", r###"Uruguay"###),
      ("UZ", r###"Uzbekistan"###),
      ("VA", r###"Vatican City"###),
      ("VC", r###"St Vincent & the Grenadines"###),
      ("VE", r###"Venezuela"###),
      ("VG", r###"British Virgin Islands"###),
      ("VI", r###"US Virgin Islands"###),
      ("VN", r###"Vietnam"###),
      ("VU", r###"Vanuatu"###),
      ("WF", r###"Wallis & Futuna"###),
      ("WS", r###"Samoa"###),
      ("XA", r###"Pseudo-Accents"###),
      ("XB", r###"Pseudo-Bidi"###),
      ("XK", r###"Kosovo"###),
      ("YE", r###"Yemen"###),
      ("YT", r###"Mayotte"###),
      ("ZA", r###"South Africa"###),
      ("ZM", r###"Zambia"###),
      ("ZW", r###"Zimbabwe"###),
      ("ZZ", r###"Unknown Region"###),
    ],
  }
}
