use super::TinyID;
/// This is a `phf::Map` constant that maps language codes to their
/// corresponding `TinyID` structs.
///
/// MAX means Maximize.
/// For example: en -> en-Latn-US
///
/// The `TinyID` struct is created using the `TinyID::new()` function, which
/// takes three arguments: `language`, `script`, and `region`. These arguments
/// represent the ISO 639-1 language code, ISO 15924 script code, and ISO 3166-1
/// alpha-2 region code for the language respectively.
///
/// ## Examples
///
/// ```
/// let map = lang_id::maps::max::map();
/// let de = &map["de"];
/// assert_eq!(de.language, "de");
/// assert_eq!(de.script, "Latn");
/// assert_eq!(de.region, "DE");
/// ```
///
/// ```
/// let map = lang_id::maps::max::map();
/// let zh = &map["zh"];
/// assert_eq!(zh.language, "zh");
/// assert_eq!(zh.script, "Hans");
/// assert_eq!(zh.region, "CN");
/// ```
pub const fn map<'m>() -> super::PhfTinyidMap<'m> {
  super::phf::OrderedMap {
    key: 12913932095322966823,
    disps: &[
      (0, 306),
      (0, 43),
      (0, 6),
      (0, 16),
      (0, 24),
      (0, 312),
      (0, 12),
      (0, 323),
      (0, 441),
      (0, 13),
      (0, 0),
      (1, 190),
      (0, 17),
      (0, 117),
      (0, 36),
      (0, 109),
      (0, 10),
      (0, 13),
      (0, 246),
      (0, 11),
      (1, 294),
      (0, 14),
      (1, 433),
      (1, 1),
      (0, 0),
      (2, 222),
      (2, 480),
      (0, 349),
      (0, 7),
      (0, 301),
      (0, 21),
      (0, 3),
      (0, 68),
      (0, 2),
      (0, 26),
      (0, 2),
      (0, 0),
      (1, 261),
      (0, 272),
      (0, 22),
      (0, 28),
      (0, 0),
      (0, 2),
      (0, 568),
      (0, 56),
      (0, 7),
      (0, 2),
      (0, 246),
      (0, 384),
      (1, 118),
      (0, 1),
      (0, 1),
      (0, 163),
      (0, 18),
      (3, 283),
      (0, 155),
      (3, 472),
      (2, 200),
      (0, 262),
      (0, 37),
      (1, 1),
      (0, 64),
      (0, 11),
      (0, 20),
      (0, 73),
      (2, 294),
      (0, 13),
      (0, 59),
      (0, 218),
      (0, 1),
      (0, 2),
      (0, 207),
      (0, 353),
      (0, 177),
      (4, 122),
      (0, 46),
      (0, 0),
      (0, 105),
      (0, 91),
      (0, 542),
      (0, 335),
      (0, 18),
      (0, 37),
      (0, 5),
      (0, 219),
      (0, 318),
      (2, 426),
      (1, 214),
      (0, 288),
      (0, 430),
      (6, 103),
      (13, 186),
      (0, 551),
      (0, 214),
      (0, 1),
      (0, 19),
      (6, 295),
      (0, 383),
      (0, 217),
      (5, 48),
      (0, 258),
      (0, 29),
      (0, 18),
      (6, 501),
      (0, 1),
      (10, 85),
      (0, 44),
      (7, 227),
      (4, 422),
      (0, 0),
      (0, 0),
      (1, 519),
      (0, 232),
      (0, 0),
      (0, 19),
      (3, 507),
      (0, 292),
      (29, 394),
      (0, 1),
    ],
    idxs: &[
      433, 527, 397, 172, 115, 578, 253, 554, 320, 177, 10, 110, 76, 469, 569, 137,
      434, 331, 511, 255, 535, 270, 498, 293, 448, 556, 123, 592, 341, 326, 184,
      384, 545, 120, 590, 91, 462, 90, 414, 566, 231, 365, 204, 249, 100, 125, 405,
      324, 132, 460, 425, 435, 0, 418, 357, 402, 544, 335, 7, 229, 180, 552, 429,
      441, 471, 238, 359, 451, 79, 196, 214, 329, 37, 502, 356, 340, 107, 239, 427,
      261, 282, 286, 234, 130, 49, 388, 134, 112, 168, 143, 118, 496, 344, 151, 430,
      179, 185, 223, 146, 272, 411, 36, 240, 394, 57, 587, 51, 350, 9, 114, 313,
      312, 220, 66, 516, 174, 157, 550, 476, 178, 190, 152, 250, 562, 206, 18, 422,
      139, 466, 546, 138, 582, 287, 585, 474, 524, 64, 515, 475, 547, 500, 373, 560,
      277, 314, 176, 41, 455, 533, 361, 164, 504, 135, 95, 573, 322, 325, 305, 539,
      58, 195, 94, 173, 431, 440, 492, 309, 593, 409, 264, 482, 87, 372, 88, 153,
      376, 310, 483, 80, 493, 11, 227, 171, 336, 63, 233, 166, 413, 404, 127, 561,
      243, 187, 108, 81, 391, 267, 4, 406, 3, 101, 48, 34, 408, 494, 315, 457, 275,
      514, 265, 295, 219, 28, 567, 245, 318, 507, 122, 119, 513, 188, 237, 89, 530,
      407, 192, 199, 296, 328, 117, 472, 591, 311, 375, 484, 228, 44, 251, 61, 512,
      346, 456, 571, 69, 241, 40, 419, 532, 377, 2, 477, 574, 202, 478, 224, 528,
      12, 129, 577, 289, 128, 579, 59, 281, 549, 509, 382, 444, 21, 225, 586, 16,
      354, 445, 165, 35, 144, 160, 230, 161, 523, 495, 432, 437, 68, 299, 362, 242,
      103, 529, 369, 75, 555, 208, 363, 26, 268, 32, 347, 207, 244, 366, 167, 464,
      470, 22, 386, 93, 565, 39, 443, 105, 360, 450, 71, 439, 300, 333, 133, 380,
      479, 481, 269, 154, 217, 370, 304, 235, 302, 428, 200, 258, 330, 442, 226,
      355, 383, 46, 189, 213, 54, 67, 65, 497, 378, 503, 274, 563, 30, 334, 308,
      584, 485, 169, 364, 570, 518, 345, 8, 410, 247, 126, 506, 197, 351, 291, 294,
      412, 271, 84, 148, 421, 191, 536, 519, 564, 517, 538, 338, 136, 222, 387, 398,
      106, 62, 491, 526, 260, 203, 505, 221, 19, 163, 368, 86, 263, 292, 52, 337,
      96, 266, 170, 14, 29, 531, 323, 581, 1, 183, 82, 33, 236, 25, 423, 319, 348,
      182, 385, 572, 297, 109, 342, 349, 520, 381, 473, 142, 541, 121, 395, 303,
      454, 218, 352, 488, 257, 47, 580, 279, 426, 5, 150, 458, 155, 141, 568, 116,
      193, 216, 20, 131, 280, 438, 583, 559, 209, 43, 147, 256, 417, 551, 306, 534,
      162, 374, 156, 201, 56, 339, 317, 301, 72, 446, 316, 13, 353, 522, 401, 327,
      248, 158, 290, 99, 149, 367, 17, 332, 486, 510, 232, 416, 390, 70, 468, 113,
      501, 283, 588, 343, 543, 459, 525, 194, 487, 73, 465, 102, 424, 403, 284, 262,
      211, 254, 50, 205, 576, 186, 276, 104, 45, 15, 461, 85, 97, 259, 540, 31, 215,
      537, 181, 140, 379, 436, 98, 288, 558, 210, 307, 389, 447, 78, 453, 83, 490,
      159, 452, 521, 38, 396, 42, 508, 393, 548, 480, 53, 553, 23, 489, 449, 252,
      77, 124, 198, 212, 400, 321, 298, 278, 467, 55, 575, 399, 111, 27, 463, 24,
      420, 92, 557, 246, 371, 392, 285, 175, 74, 60, 542, 6, 589, 415, 145, 273,
      358, 499,
    ],
    entries: &[
      ("af", const { TinyID::new("af", "Latn", "ZA") }),
      ("af-NA", const { TinyID::new("af", "Latn", "NA") }),
      ("agq", const { TinyID::new("agq", "Latn", "CM") }),
      ("ak", const { TinyID::new("ak", "Latn", "GH") }),
      ("am", const { TinyID::new("am", "Ethi", "ET") }),
      ("ann", const { TinyID::new("ann", "Latn", "NG") }),
      ("ar", const { TinyID::new("ar", "Arab", "EG") }),
      ("ar-AE", const { TinyID::new("ar", "Arab", "AE") }),
      ("ar-BH", const { TinyID::new("ar", "Arab", "BH") }),
      ("ar-DJ", const { TinyID::new("ar", "Arab", "DJ") }),
      ("ar-DZ", const { TinyID::new("ar", "Arab", "DZ") }),
      ("ar-EG", const { TinyID::new("ar", "Arab", "EG") }),
      ("ar-EH", const { TinyID::new("ar", "Arab", "EH") }),
      ("ar-ER", const { TinyID::new("ar", "Arab", "ER") }),
      ("ar-IL", const { TinyID::new("ar", "Arab", "IL") }),
      ("ar-IQ", const { TinyID::new("ar", "Arab", "IQ") }),
      ("ar-JO", const { TinyID::new("ar", "Arab", "JO") }),
      ("ar-KM", const { TinyID::new("ar", "Arab", "KM") }),
      ("ar-KW", const { TinyID::new("ar", "Arab", "KW") }),
      ("ar-LB", const { TinyID::new("ar", "Arab", "LB") }),
      ("ar-LY", const { TinyID::new("ar", "Arab", "LY") }),
      ("ar-MA", const { TinyID::new("ar", "Arab", "MA") }),
      ("ar-MR", const { TinyID::new("ar", "Arab", "MR") }),
      ("ar-OM", const { TinyID::new("ar", "Arab", "OM") }),
      ("ar-PS", const { TinyID::new("ar", "Arab", "PS") }),
      ("ar-QA", const { TinyID::new("ar", "Arab", "QA") }),
      ("ar-SA", const { TinyID::new("ar", "Arab", "SA") }),
      ("ar-SD", const { TinyID::new("ar", "Arab", "SD") }),
      ("ar-SO", const { TinyID::new("ar", "Arab", "SO") }),
      ("ar-SS", const { TinyID::new("ar", "Arab", "SS") }),
      ("ar-SY", const { TinyID::new("ar", "Arab", "SY") }),
      ("ar-TD", const { TinyID::new("ar", "Arab", "TD") }),
      ("ar-TN", const { TinyID::new("ar", "Arab", "TN") }),
      ("ar-YE", const { TinyID::new("ar", "Arab", "YE") }),
      ("as", const { TinyID::new("as", "Beng", "IN") }),
      ("asa", const { TinyID::new("asa", "Latn", "TZ") }),
      ("ast", const { TinyID::new("ast", "Latn", "ES") }),
      ("az", const { TinyID::new("az", "Latn", "AZ") }),
      ("az-Cyrl", const { TinyID::new("az", "Cyrl", "AZ") }),
      ("az-Latn", const { TinyID::new("az", "Latn", "AZ") }),
      ("bas", const { TinyID::new("bas", "Latn", "CM") }),
      ("be", const { TinyID::new("be", "Cyrl", "BY") }),
      ("bem", const { TinyID::new("bem", "Latn", "ZM") }),
      ("bez", const { TinyID::new("bez", "Latn", "TZ") }),
      ("bg", const { TinyID::new("bg", "Cyrl", "BG") }),
      ("bgc", const { TinyID::new("bgc", "Deva", "IN") }),
      ("bho", const { TinyID::new("bho", "Deva", "IN") }),
      ("bm", const { TinyID::new("bm", "Latn", "ML") }),
      ("bn", const { TinyID::new("bn", "Beng", "BD") }),
      ("bn-IN", const { TinyID::new("bn", "Beng", "IN") }),
      ("bo", const { TinyID::new("bo", "Tibt", "CN") }),
      ("bo-IN", const { TinyID::new("bo", "Tibt", "IN") }),
      ("br", const { TinyID::new("br", "Latn", "FR") }),
      ("brx", const { TinyID::new("brx", "Deva", "IN") }),
      ("bs", const { TinyID::new("bs", "Latn", "BA") }),
      ("bs-Cyrl", const { TinyID::new("bs", "Cyrl", "BA") }),
      ("bs-Latn", const { TinyID::new("bs", "Latn", "BA") }),
      ("ca", const { TinyID::new("ca", "Latn", "ES") }),
      ("ca-AD", const { TinyID::new("ca", "Latn", "AD") }),
      ("ca-FR", const { TinyID::new("ca", "Latn", "FR") }),
      ("ca-IT", const { TinyID::new("ca", "Latn", "IT") }),
      ("ccp", const { TinyID::new("ccp", "Cakm", "BD") }),
      ("ccp-IN", const { TinyID::new("ccp", "Cakm", "IN") }),
      ("ce", const { TinyID::new("ce", "Cyrl", "RU") }),
      ("ceb", const { TinyID::new("ceb", "Latn", "PH") }),
      ("cgg", const { TinyID::new("cgg", "Latn", "UG") }),
      ("chr", const { TinyID::new("chr", "Cher", "US") }),
      ("ckb", const { TinyID::new("ckb", "Arab", "IQ") }),
      ("ckb-IR", const { TinyID::new("ckb", "Arab", "IR") }),
      ("cs", const { TinyID::new("cs", "Latn", "CZ") }),
      ("cv", const { TinyID::new("cv", "Cyrl", "RU") }),
      ("cy", const { TinyID::new("cy", "Latn", "GB") }),
      ("da", const { TinyID::new("da", "Latn", "DK") }),
      ("da-GL", const { TinyID::new("da", "Latn", "GL") }),
      ("dav", const { TinyID::new("dav", "Latn", "KE") }),
      ("de", const { TinyID::new("de", "Latn", "DE") }),
      ("de-AT", const { TinyID::new("de", "Latn", "AT") }),
      ("de-BE", const { TinyID::new("de", "Latn", "BE") }),
      ("de-CH", const { TinyID::new("de", "Latn", "CH") }),
      ("de-IT", const { TinyID::new("de", "Latn", "IT") }),
      ("de-LI", const { TinyID::new("de", "Latn", "LI") }),
      ("de-LU", const { TinyID::new("de", "Latn", "LU") }),
      ("dje", const { TinyID::new("dje", "Latn", "NE") }),
      ("doi", const { TinyID::new("doi", "Deva", "IN") }),
      ("dsb", const { TinyID::new("dsb", "Latn", "DE") }),
      ("dua", const { TinyID::new("dua", "Latn", "CM") }),
      ("dyo", const { TinyID::new("dyo", "Latn", "SN") }),
      ("dz", const { TinyID::new("dz", "Tibt", "BT") }),
      ("ebu", const { TinyID::new("ebu", "Latn", "KE") }),
      ("ee", const { TinyID::new("ee", "Latn", "GH") }),
      ("ee-TG", const { TinyID::new("ee", "Latn", "TG") }),
      ("el", const { TinyID::new("el", "Grek", "GR") }),
      ("el-CY", const { TinyID::new("el", "Grek", "CY") }),
      ("en", const { TinyID::new("en", "Latn", "US") }),
      ("en-001", const { TinyID::new("en", "Latn", "001") }),
      ("en-150", const { TinyID::new("en", "Latn", "150") }),
      ("en-AE", const { TinyID::new("en", "Latn", "AE") }),
      ("en-AG", const { TinyID::new("en", "Latn", "AG") }),
      ("en-AI", const { TinyID::new("en", "Latn", "AI") }),
      ("en-AS", const { TinyID::new("en", "Latn", "AS") }),
      ("en-AT", const { TinyID::new("en", "Latn", "AT") }),
      ("en-AU", const { TinyID::new("en", "Latn", "AU") }),
      ("en-BB", const { TinyID::new("en", "Latn", "BB") }),
      ("en-BE", const { TinyID::new("en", "Latn", "BE") }),
      ("en-BI", const { TinyID::new("en", "Latn", "BI") }),
      ("en-BM", const { TinyID::new("en", "Latn", "BM") }),
      ("en-BS", const { TinyID::new("en", "Latn", "BS") }),
      ("en-BW", const { TinyID::new("en", "Latn", "BW") }),
      ("en-BZ", const { TinyID::new("en", "Latn", "BZ") }),
      ("en-CA", const { TinyID::new("en", "Latn", "CA") }),
      ("en-CC", const { TinyID::new("en", "Latn", "CC") }),
      ("en-CH", const { TinyID::new("en", "Latn", "CH") }),
      ("en-CK", const { TinyID::new("en", "Latn", "CK") }),
      ("en-CM", const { TinyID::new("en", "Latn", "CM") }),
      ("en-CX", const { TinyID::new("en", "Latn", "CX") }),
      ("en-CY", const { TinyID::new("en", "Latn", "CY") }),
      ("en-DE", const { TinyID::new("en", "Latn", "DE") }),
      ("en-DG", const { TinyID::new("en", "Latn", "DG") }),
      ("en-DK", const { TinyID::new("en", "Latn", "DK") }),
      ("en-DM", const { TinyID::new("en", "Latn", "DM") }),
      ("en-ER", const { TinyID::new("en", "Latn", "ER") }),
      ("en-FI", const { TinyID::new("en", "Latn", "FI") }),
      ("en-FJ", const { TinyID::new("en", "Latn", "FJ") }),
      ("en-FK", const { TinyID::new("en", "Latn", "FK") }),
      ("en-FM", const { TinyID::new("en", "Latn", "FM") }),
      ("en-GB", const { TinyID::new("en", "Latn", "GB") }),
      ("en-GD", const { TinyID::new("en", "Latn", "GD") }),
      ("en-GG", const { TinyID::new("en", "Latn", "GG") }),
      ("en-GH", const { TinyID::new("en", "Latn", "GH") }),
      ("en-GI", const { TinyID::new("en", "Latn", "GI") }),
      ("en-GM", const { TinyID::new("en", "Latn", "GM") }),
      ("en-GU", const { TinyID::new("en", "Latn", "GU") }),
      ("en-GY", const { TinyID::new("en", "Latn", "GY") }),
      ("en-HK", const { TinyID::new("en", "Latn", "HK") }),
      ("en-IE", const { TinyID::new("en", "Latn", "IE") }),
      ("en-IL", const { TinyID::new("en", "Latn", "IL") }),
      ("en-IM", const { TinyID::new("en", "Latn", "IM") }),
      ("en-IN", const { TinyID::new("en", "Latn", "IN") }),
      ("en-IO", const { TinyID::new("en", "Latn", "IO") }),
      ("en-JE", const { TinyID::new("en", "Latn", "JE") }),
      ("en-JM", const { TinyID::new("en", "Latn", "JM") }),
      ("en-KE", const { TinyID::new("en", "Latn", "KE") }),
      ("en-KI", const { TinyID::new("en", "Latn", "KI") }),
      ("en-KN", const { TinyID::new("en", "Latn", "KN") }),
      ("en-KY", const { TinyID::new("en", "Latn", "KY") }),
      ("en-LC", const { TinyID::new("en", "Latn", "LC") }),
      ("en-LR", const { TinyID::new("en", "Latn", "LR") }),
      ("en-LS", const { TinyID::new("en", "Latn", "LS") }),
      ("en-MG", const { TinyID::new("en", "Latn", "MG") }),
      ("en-MH", const { TinyID::new("en", "Latn", "MH") }),
      ("en-MO", const { TinyID::new("en", "Latn", "MO") }),
      ("en-MP", const { TinyID::new("en", "Latn", "MP") }),
      ("en-MS", const { TinyID::new("en", "Latn", "MS") }),
      ("en-MT", const { TinyID::new("en", "Latn", "MT") }),
      ("en-MU", const { TinyID::new("en", "Latn", "MU") }),
      ("en-MV", const { TinyID::new("en", "Latn", "MV") }),
      ("en-MW", const { TinyID::new("en", "Latn", "MW") }),
      ("en-MY", const { TinyID::new("en", "Latn", "MY") }),
      ("en-NA", const { TinyID::new("en", "Latn", "NA") }),
      ("en-NF", const { TinyID::new("en", "Latn", "NF") }),
      ("en-NG", const { TinyID::new("en", "Latn", "NG") }),
      ("en-NL", const { TinyID::new("en", "Latn", "NL") }),
      ("en-NR", const { TinyID::new("en", "Latn", "NR") }),
      ("en-NU", const { TinyID::new("en", "Latn", "NU") }),
      ("en-NZ", const { TinyID::new("en", "Latn", "NZ") }),
      ("en-PG", const { TinyID::new("en", "Latn", "PG") }),
      ("en-PH", const { TinyID::new("en", "Latn", "PH") }),
      ("en-PK", const { TinyID::new("en", "Latn", "PK") }),
      ("en-PN", const { TinyID::new("en", "Latn", "PN") }),
      ("en-PR", const { TinyID::new("en", "Latn", "PR") }),
      ("en-PW", const { TinyID::new("en", "Latn", "PW") }),
      ("en-RW", const { TinyID::new("en", "Latn", "RW") }),
      ("en-SB", const { TinyID::new("en", "Latn", "SB") }),
      ("en-SC", const { TinyID::new("en", "Latn", "SC") }),
      ("en-SD", const { TinyID::new("en", "Latn", "SD") }),
      ("en-SE", const { TinyID::new("en", "Latn", "SE") }),
      ("en-SG", const { TinyID::new("en", "Latn", "SG") }),
      ("en-SH", const { TinyID::new("en", "Latn", "SH") }),
      ("en-SI", const { TinyID::new("en", "Latn", "SI") }),
      ("en-SL", const { TinyID::new("en", "Latn", "SL") }),
      ("en-SS", const { TinyID::new("en", "Latn", "SS") }),
      ("en-SX", const { TinyID::new("en", "Latn", "SX") }),
      ("en-SZ", const { TinyID::new("en", "Latn", "SZ") }),
      ("en-TC", const { TinyID::new("en", "Latn", "TC") }),
      ("en-TK", const { TinyID::new("en", "Latn", "TK") }),
      ("en-TO", const { TinyID::new("en", "Latn", "TO") }),
      ("en-TT", const { TinyID::new("en", "Latn", "TT") }),
      ("en-TV", const { TinyID::new("en", "Latn", "TV") }),
      ("en-TZ", const { TinyID::new("en", "Latn", "TZ") }),
      ("en-UG", const { TinyID::new("en", "Latn", "UG") }),
      ("en-UM", const { TinyID::new("en", "Latn", "UM") }),
      ("en-VC", const { TinyID::new("en", "Latn", "VC") }),
      ("en-VG", const { TinyID::new("en", "Latn", "VG") }),
      ("en-VI", const { TinyID::new("en", "Latn", "VI") }),
      ("en-VU", const { TinyID::new("en", "Latn", "VU") }),
      ("en-WS", const { TinyID::new("en", "Latn", "WS") }),
      ("en-ZA", const { TinyID::new("en", "Latn", "ZA") }),
      ("en-ZM", const { TinyID::new("en", "Latn", "ZM") }),
      ("en-ZW", const { TinyID::new("en", "Latn", "ZW") }),
      ("eo", const { TinyID::new("eo", "Latn", "001") }),
      ("es", const { TinyID::new("es", "Latn", "ES") }),
      ("es-419", const { TinyID::new("es", "Latn", "419") }),
      ("es-AR", const { TinyID::new("es", "Latn", "AR") }),
      ("es-BO", const { TinyID::new("es", "Latn", "BO") }),
      ("es-BR", const { TinyID::new("es", "Latn", "BR") }),
      ("es-BZ", const { TinyID::new("es", "Latn", "BZ") }),
      ("es-CL", const { TinyID::new("es", "Latn", "CL") }),
      ("es-CO", const { TinyID::new("es", "Latn", "CO") }),
      ("es-CR", const { TinyID::new("es", "Latn", "CR") }),
      ("es-CU", const { TinyID::new("es", "Latn", "CU") }),
      ("es-DO", const { TinyID::new("es", "Latn", "DO") }),
      ("es-EA", const { TinyID::new("es", "Latn", "EA") }),
      ("es-EC", const { TinyID::new("es", "Latn", "EC") }),
      ("es-GQ", const { TinyID::new("es", "Latn", "GQ") }),
      ("es-GT", const { TinyID::new("es", "Latn", "GT") }),
      ("es-HN", const { TinyID::new("es", "Latn", "HN") }),
      ("es-IC", const { TinyID::new("es", "Latn", "IC") }),
      ("es-MX", const { TinyID::new("es", "Latn", "MX") }),
      ("es-NI", const { TinyID::new("es", "Latn", "NI") }),
      ("es-PA", const { TinyID::new("es", "Latn", "PA") }),
      ("es-PE", const { TinyID::new("es", "Latn", "PE") }),
      ("es-PH", const { TinyID::new("es", "Latn", "PH") }),
      ("es-PR", const { TinyID::new("es", "Latn", "PR") }),
      ("es-PY", const { TinyID::new("es", "Latn", "PY") }),
      ("es-SV", const { TinyID::new("es", "Latn", "SV") }),
      ("es-US", const { TinyID::new("es", "Latn", "US") }),
      ("es-UY", const { TinyID::new("es", "Latn", "UY") }),
      ("es-VE", const { TinyID::new("es", "Latn", "VE") }),
      ("et", const { TinyID::new("et", "Latn", "EE") }),
      ("eu", const { TinyID::new("eu", "Latn", "ES") }),
      ("ewo", const { TinyID::new("ewo", "Latn", "CM") }),
      ("fa", const { TinyID::new("fa", "Arab", "IR") }),
      ("fa-AF", const { TinyID::new("fa", "Arab", "AF") }),
      ("ff", const { TinyID::new("ff", "Latn", "SN") }),
      ("ff-Adlm", const { TinyID::new("ff", "Adlm", "GN") }),
      ("ff-Adlm-BF", const { TinyID::new("ff", "Adlm", "BF") }),
      ("ff-Adlm-CM", const { TinyID::new("ff", "Adlm", "CM") }),
      ("ff-Adlm-GH", const { TinyID::new("ff", "Adlm", "GH") }),
      ("ff-Adlm-GM", const { TinyID::new("ff", "Adlm", "GM") }),
      ("ff-Adlm-GW", const { TinyID::new("ff", "Adlm", "GW") }),
      ("ff-Adlm-LR", const { TinyID::new("ff", "Adlm", "LR") }),
      ("ff-Adlm-MR", const { TinyID::new("ff", "Adlm", "MR") }),
      ("ff-Adlm-NE", const { TinyID::new("ff", "Adlm", "NE") }),
      ("ff-Adlm-NG", const { TinyID::new("ff", "Adlm", "NG") }),
      ("ff-Adlm-SL", const { TinyID::new("ff", "Adlm", "SL") }),
      ("ff-Adlm-SN", const { TinyID::new("ff", "Adlm", "SN") }),
      ("ff-Latn", const { TinyID::new("ff", "Latn", "SN") }),
      ("ff-Latn-BF", const { TinyID::new("ff", "Latn", "BF") }),
      ("ff-Latn-CM", const { TinyID::new("ff", "Latn", "CM") }),
      ("ff-Latn-GH", const { TinyID::new("ff", "Latn", "GH") }),
      ("ff-Latn-GM", const { TinyID::new("ff", "Latn", "GM") }),
      ("ff-Latn-GN", const { TinyID::new("ff", "Latn", "GN") }),
      ("ff-Latn-GW", const { TinyID::new("ff", "Latn", "GW") }),
      ("ff-Latn-LR", const { TinyID::new("ff", "Latn", "LR") }),
      ("ff-Latn-MR", const { TinyID::new("ff", "Latn", "MR") }),
      ("ff-Latn-NE", const { TinyID::new("ff", "Latn", "NE") }),
      ("ff-Latn-NG", const { TinyID::new("ff", "Latn", "NG") }),
      ("ff-Latn-SL", const { TinyID::new("ff", "Latn", "SL") }),
      ("fi", const { TinyID::new("fi", "Latn", "FI") }),
      ("fil", const { TinyID::new("fil", "Latn", "PH") }),
      ("fo", const { TinyID::new("fo", "Latn", "FO") }),
      ("fo-DK", const { TinyID::new("fo", "Latn", "DK") }),
      ("fr", const { TinyID::new("fr", "Latn", "FR") }),
      ("fr-BE", const { TinyID::new("fr", "Latn", "BE") }),
      ("fr-BF", const { TinyID::new("fr", "Latn", "BF") }),
      ("fr-BI", const { TinyID::new("fr", "Latn", "BI") }),
      ("fr-BJ", const { TinyID::new("fr", "Latn", "BJ") }),
      ("fr-BL", const { TinyID::new("fr", "Latn", "BL") }),
      ("fr-CA", const { TinyID::new("fr", "Latn", "CA") }),
      ("fr-CD", const { TinyID::new("fr", "Latn", "CD") }),
      ("fr-CF", const { TinyID::new("fr", "Latn", "CF") }),
      ("fr-CG", const { TinyID::new("fr", "Latn", "CG") }),
      ("fr-CH", const { TinyID::new("fr", "Latn", "CH") }),
      ("fr-CI", const { TinyID::new("fr", "Latn", "CI") }),
      ("fr-CM", const { TinyID::new("fr", "Latn", "CM") }),
      ("fr-DJ", const { TinyID::new("fr", "Latn", "DJ") }),
      ("fr-DZ", const { TinyID::new("fr", "Latn", "DZ") }),
      ("fr-GA", const { TinyID::new("fr", "Latn", "GA") }),
      ("fr-GF", const { TinyID::new("fr", "Latn", "GF") }),
      ("fr-GN", const { TinyID::new("fr", "Latn", "GN") }),
      ("fr-GP", const { TinyID::new("fr", "Latn", "GP") }),
      ("fr-GQ", const { TinyID::new("fr", "Latn", "GQ") }),
      ("fr-HT", const { TinyID::new("fr", "Latn", "HT") }),
      ("fr-KM", const { TinyID::new("fr", "Latn", "KM") }),
      ("fr-LU", const { TinyID::new("fr", "Latn", "LU") }),
      ("fr-MA", const { TinyID::new("fr", "Latn", "MA") }),
      ("fr-MC", const { TinyID::new("fr", "Latn", "MC") }),
      ("fr-MF", const { TinyID::new("fr", "Latn", "MF") }),
      ("fr-MG", const { TinyID::new("fr", "Latn", "MG") }),
      ("fr-ML", const { TinyID::new("fr", "Latn", "ML") }),
      ("fr-MQ", const { TinyID::new("fr", "Latn", "MQ") }),
      ("fr-MR", const { TinyID::new("fr", "Latn", "MR") }),
      ("fr-MU", const { TinyID::new("fr", "Latn", "MU") }),
      ("fr-NC", const { TinyID::new("fr", "Latn", "NC") }),
      ("fr-NE", const { TinyID::new("fr", "Latn", "NE") }),
      ("fr-PF", const { TinyID::new("fr", "Latn", "PF") }),
      ("fr-PM", const { TinyID::new("fr", "Latn", "PM") }),
      ("fr-RE", const { TinyID::new("fr", "Latn", "RE") }),
      ("fr-RW", const { TinyID::new("fr", "Latn", "RW") }),
      ("fr-SC", const { TinyID::new("fr", "Latn", "SC") }),
      ("fr-SN", const { TinyID::new("fr", "Latn", "SN") }),
      ("fr-SY", const { TinyID::new("fr", "Latn", "SY") }),
      ("fr-TD", const { TinyID::new("fr", "Latn", "TD") }),
      ("fr-TG", const { TinyID::new("fr", "Latn", "TG") }),
      ("fr-TN", const { TinyID::new("fr", "Latn", "TN") }),
      ("fr-VU", const { TinyID::new("fr", "Latn", "VU") }),
      ("fr-WF", const { TinyID::new("fr", "Latn", "WF") }),
      ("fr-YT", const { TinyID::new("fr", "Latn", "YT") }),
      ("frr", const { TinyID::new("frr", "Latn", "DE") }),
      ("fur", const { TinyID::new("fur", "Latn", "IT") }),
      ("fy", const { TinyID::new("fy", "Latn", "NL") }),
      ("ga", const { TinyID::new("ga", "Latn", "IE") }),
      ("ga-GB", const { TinyID::new("ga", "Latn", "GB") }),
      ("gd", const { TinyID::new("gd", "Latn", "GB") }),
      ("gl", const { TinyID::new("gl", "Latn", "ES") }),
      ("gsw", const { TinyID::new("gsw", "Latn", "CH") }),
      ("gsw-FR", const { TinyID::new("gsw", "Latn", "FR") }),
      ("gsw-LI", const { TinyID::new("gsw", "Latn", "LI") }),
      ("gu", const { TinyID::new("gu", "Gujr", "IN") }),
      ("guz", const { TinyID::new("guz", "Latn", "KE") }),
      ("gv", const { TinyID::new("gv", "Latn", "IM") }),
      ("ha", const { TinyID::new("ha", "Latn", "NG") }),
      ("ha-GH", const { TinyID::new("ha", "Latn", "GH") }),
      ("ha-NE", const { TinyID::new("ha", "Latn", "NE") }),
      ("haw", const { TinyID::new("haw", "Latn", "US") }),
      ("he", const { TinyID::new("he", "Hebr", "IL") }),
      ("hi", const { TinyID::new("hi", "Deva", "IN") }),
      ("hi-Latn", const { TinyID::new("hi", "Latn", "IN") }),
      ("hr", const { TinyID::new("hr", "Latn", "HR") }),
      ("hr-BA", const { TinyID::new("hr", "Latn", "BA") }),
      ("hsb", const { TinyID::new("hsb", "Latn", "DE") }),
      ("hu", const { TinyID::new("hu", "Latn", "HU") }),
      ("hy", const { TinyID::new("hy", "Armn", "AM") }),
      ("ia", const { TinyID::new("ia", "Latn", "001") }),
      ("id", const { TinyID::new("id", "Latn", "ID") }),
      ("ig", const { TinyID::new("ig", "Latn", "NG") }),
      ("ii", const { TinyID::new("ii", "Yiii", "CN") }),
      ("is", const { TinyID::new("is", "Latn", "IS") }),
      ("it", const { TinyID::new("it", "Latn", "IT") }),
      ("it-CH", const { TinyID::new("it", "Latn", "CH") }),
      ("it-SM", const { TinyID::new("it", "Latn", "SM") }),
      ("it-VA", const { TinyID::new("it", "Latn", "VA") }),
      ("ja", const { TinyID::new("ja", "Jpan", "JP") }),
      ("jgo", const { TinyID::new("jgo", "Latn", "CM") }),
      ("jmc", const { TinyID::new("jmc", "Latn", "TZ") }),
      ("jv", const { TinyID::new("jv", "Latn", "ID") }),
      ("ka", const { TinyID::new("ka", "Geor", "GE") }),
      ("kab", const { TinyID::new("kab", "Latn", "DZ") }),
      ("kam", const { TinyID::new("kam", "Latn", "KE") }),
      ("kde", const { TinyID::new("kde", "Latn", "TZ") }),
      ("kea", const { TinyID::new("kea", "Latn", "CV") }),
      ("kgp", const { TinyID::new("kgp", "Latn", "BR") }),
      ("khq", const { TinyID::new("khq", "Latn", "ML") }),
      ("ki", const { TinyID::new("ki", "Latn", "KE") }),
      ("kk", const { TinyID::new("kk", "Cyrl", "KZ") }),
      ("kkj", const { TinyID::new("kkj", "Latn", "CM") }),
      ("kl", const { TinyID::new("kl", "Latn", "GL") }),
      ("kln", const { TinyID::new("kln", "Latn", "KE") }),
      ("km", const { TinyID::new("km", "Khmr", "KH") }),
      ("kn", const { TinyID::new("kn", "Knda", "IN") }),
      ("ko", const { TinyID::new("ko", "Kore", "KR") }),
      ("ko-KP", const { TinyID::new("ko", "Kore", "KP") }),
      ("kok", const { TinyID::new("kok", "Deva", "IN") }),
      ("ks", const { TinyID::new("ks", "Arab", "IN") }),
      ("ks-Arab", const { TinyID::new("ks", "Arab", "IN") }),
      ("ks-Deva", const { TinyID::new("ks", "Deva", "IN") }),
      ("ksb", const { TinyID::new("ksb", "Latn", "TZ") }),
      ("ksf", const { TinyID::new("ksf", "Latn", "CM") }),
      ("ksh", const { TinyID::new("ksh", "Latn", "DE") }),
      ("ku", const { TinyID::new("ku", "Latn", "TR") }),
      ("kw", const { TinyID::new("kw", "Latn", "GB") }),
      ("ky", const { TinyID::new("ky", "Cyrl", "KG") }),
      ("lag", const { TinyID::new("lag", "Latn", "TZ") }),
      ("lb", const { TinyID::new("lb", "Latn", "LU") }),
      ("lg", const { TinyID::new("lg", "Latn", "UG") }),
      ("lkt", const { TinyID::new("lkt", "Latn", "US") }),
      ("ln", const { TinyID::new("ln", "Latn", "CD") }),
      ("ln-AO", const { TinyID::new("ln", "Latn", "AO") }),
      ("ln-CF", const { TinyID::new("ln", "Latn", "CF") }),
      ("ln-CG", const { TinyID::new("ln", "Latn", "CG") }),
      ("lo", const { TinyID::new("lo", "Laoo", "LA") }),
      ("lrc", const { TinyID::new("lrc", "Arab", "IR") }),
      ("lrc-IQ", const { TinyID::new("lrc", "Arab", "IQ") }),
      ("lt", const { TinyID::new("lt", "Latn", "LT") }),
      ("lu", const { TinyID::new("lu", "Latn", "CD") }),
      ("luo", const { TinyID::new("luo", "Latn", "KE") }),
      ("luy", const { TinyID::new("luy", "Latn", "KE") }),
      ("lv", const { TinyID::new("lv", "Latn", "LV") }),
      ("mai", const { TinyID::new("mai", "Deva", "IN") }),
      ("mas", const { TinyID::new("mas", "Latn", "KE") }),
      ("mas-TZ", const { TinyID::new("mas", "Latn", "TZ") }),
      ("mdf", const { TinyID::new("mdf", "Cyrl", "RU") }),
      ("mer", const { TinyID::new("mer", "Latn", "KE") }),
      ("mfe", const { TinyID::new("mfe", "Latn", "MU") }),
      ("mg", const { TinyID::new("mg", "Latn", "MG") }),
      ("mgh", const { TinyID::new("mgh", "Latn", "MZ") }),
      ("mgo", const { TinyID::new("mgo", "Latn", "CM") }),
      ("mi", const { TinyID::new("mi", "Latn", "NZ") }),
      ("mk", const { TinyID::new("mk", "Cyrl", "MK") }),
      ("ml", const { TinyID::new("ml", "Mlym", "IN") }),
      ("mn", const { TinyID::new("mn", "Cyrl", "MN") }),
      ("mni", const { TinyID::new("mni", "Beng", "IN") }),
      ("mni-Beng", const { TinyID::new("mni", "Beng", "IN") }),
      ("mr", const { TinyID::new("mr", "Deva", "IN") }),
      ("ms", const { TinyID::new("ms", "Latn", "MY") }),
      ("ms-BN", const { TinyID::new("ms", "Latn", "BN") }),
      ("ms-ID", const { TinyID::new("ms", "Latn", "ID") }),
      ("ms-SG", const { TinyID::new("ms", "Latn", "SG") }),
      ("mt", const { TinyID::new("mt", "Latn", "MT") }),
      ("mua", const { TinyID::new("mua", "Latn", "CM") }),
      ("my", const { TinyID::new("my", "Mymr", "MM") }),
      ("mzn", const { TinyID::new("mzn", "Arab", "IR") }),
      ("naq", const { TinyID::new("naq", "Latn", "NA") }),
      ("nb", const { TinyID::new("nb", "Latn", "NO") }),
      ("nb-SJ", const { TinyID::new("nb", "Latn", "SJ") }),
      ("nd", const { TinyID::new("nd", "Latn", "ZW") }),
      ("nds", const { TinyID::new("nds", "Latn", "DE") }),
      ("nds-NL", const { TinyID::new("nds", "Latn", "NL") }),
      ("ne", const { TinyID::new("ne", "Deva", "NP") }),
      ("ne-IN", const { TinyID::new("ne", "Deva", "IN") }),
      ("nl", const { TinyID::new("nl", "Latn", "NL") }),
      ("nl-AW", const { TinyID::new("nl", "Latn", "AW") }),
      ("nl-BE", const { TinyID::new("nl", "Latn", "BE") }),
      ("nl-BQ", const { TinyID::new("nl", "Latn", "BQ") }),
      ("nl-CW", const { TinyID::new("nl", "Latn", "CW") }),
      ("nl-SR", const { TinyID::new("nl", "Latn", "SR") }),
      ("nl-SX", const { TinyID::new("nl", "Latn", "SX") }),
      ("nmg", const { TinyID::new("nmg", "Latn", "CM") }),
      ("nn", const { TinyID::new("nn", "Latn", "NO") }),
      ("nnh", const { TinyID::new("nnh", "Latn", "CM") }),
      ("no", const { TinyID::new("no", "Latn", "NO") }),
      ("nus", const { TinyID::new("nus", "Latn", "SS") }),
      ("nyn", const { TinyID::new("nyn", "Latn", "UG") }),
      ("oc", const { TinyID::new("oc", "Latn", "FR") }),
      ("oc-ES", const { TinyID::new("oc", "Latn", "ES") }),
      ("om", const { TinyID::new("om", "Latn", "ET") }),
      ("om-KE", const { TinyID::new("om", "Latn", "KE") }),
      ("or", const { TinyID::new("or", "Orya", "IN") }),
      ("os", const { TinyID::new("os", "Cyrl", "GE") }),
      ("os-RU", const { TinyID::new("os", "Cyrl", "RU") }),
      ("pa", const { TinyID::new("pa", "Guru", "IN") }),
      ("pa-Arab", const { TinyID::new("pa", "Arab", "PK") }),
      ("pa-Guru", const { TinyID::new("pa", "Guru", "IN") }),
      ("pcm", const { TinyID::new("pcm", "Latn", "NG") }),
      ("pis", const { TinyID::new("pis", "Latn", "SB") }),
      ("pl", const { TinyID::new("pl", "Latn", "PL") }),
      ("ps", const { TinyID::new("ps", "Arab", "AF") }),
      ("ps-PK", const { TinyID::new("ps", "Arab", "PK") }),
      ("pt", const { TinyID::new("pt", "Latn", "BR") }),
      ("pt-AO", const { TinyID::new("pt", "Latn", "AO") }),
      ("pt-CH", const { TinyID::new("pt", "Latn", "CH") }),
      ("pt-CV", const { TinyID::new("pt", "Latn", "CV") }),
      ("pt-GQ", const { TinyID::new("pt", "Latn", "GQ") }),
      ("pt-GW", const { TinyID::new("pt", "Latn", "GW") }),
      ("pt-LU", const { TinyID::new("pt", "Latn", "LU") }),
      ("pt-MO", const { TinyID::new("pt", "Latn", "MO") }),
      ("pt-MZ", const { TinyID::new("pt", "Latn", "MZ") }),
      ("pt-PT", const { TinyID::new("pt", "Latn", "PT") }),
      ("pt-ST", const { TinyID::new("pt", "Latn", "ST") }),
      ("pt-TL", const { TinyID::new("pt", "Latn", "TL") }),
      ("qu", const { TinyID::new("qu", "Latn", "PE") }),
      ("qu-BO", const { TinyID::new("qu", "Latn", "BO") }),
      ("qu-EC", const { TinyID::new("qu", "Latn", "EC") }),
      ("raj", const { TinyID::new("raj", "Deva", "IN") }),
      ("rm", const { TinyID::new("rm", "Latn", "CH") }),
      ("rn", const { TinyID::new("rn", "Latn", "BI") }),
      ("ro", const { TinyID::new("ro", "Latn", "RO") }),
      ("ro-MD", const { TinyID::new("ro", "Latn", "MD") }),
      ("rof", const { TinyID::new("rof", "Latn", "TZ") }),
      ("ru", const { TinyID::new("ru", "Cyrl", "RU") }),
      ("ru-BY", const { TinyID::new("ru", "Cyrl", "BY") }),
      ("ru-KG", const { TinyID::new("ru", "Cyrl", "KG") }),
      ("ru-KZ", const { TinyID::new("ru", "Cyrl", "KZ") }),
      ("ru-MD", const { TinyID::new("ru", "Cyrl", "MD") }),
      ("ru-UA", const { TinyID::new("ru", "Cyrl", "UA") }),
      ("rw", const { TinyID::new("rw", "Latn", "RW") }),
      ("rwk", const { TinyID::new("rwk", "Latn", "TZ") }),
      ("sa", const { TinyID::new("sa", "Deva", "IN") }),
      ("sah", const { TinyID::new("sah", "Cyrl", "RU") }),
      ("saq", const { TinyID::new("saq", "Latn", "KE") }),
      ("sat", const { TinyID::new("sat", "Olck", "IN") }),
      ("sat-Olck", const { TinyID::new("sat", "Olck", "IN") }),
      ("sbp", const { TinyID::new("sbp", "Latn", "TZ") }),
      ("sc", const { TinyID::new("sc", "Latn", "IT") }),
      ("sd", const { TinyID::new("sd", "Arab", "PK") }),
      ("sd-Arab", const { TinyID::new("sd", "Arab", "PK") }),
      ("sd-Deva", const { TinyID::new("sd", "Deva", "IN") }),
      ("se", const { TinyID::new("se", "Latn", "NO") }),
      ("se-FI", const { TinyID::new("se", "Latn", "FI") }),
      ("se-SE", const { TinyID::new("se", "Latn", "SE") }),
      ("seh", const { TinyID::new("seh", "Latn", "MZ") }),
      ("ses", const { TinyID::new("ses", "Latn", "ML") }),
      ("sg", const { TinyID::new("sg", "Latn", "CF") }),
      ("shi", const { TinyID::new("shi", "Tfng", "MA") }),
      ("shi-Latn", const { TinyID::new("shi", "Latn", "MA") }),
      ("shi-Tfng", const { TinyID::new("shi", "Tfng", "MA") }),
      ("si", const { TinyID::new("si", "Sinh", "LK") }),
      ("sk", const { TinyID::new("sk", "Latn", "SK") }),
      ("sl", const { TinyID::new("sl", "Latn", "SI") }),
      ("smn", const { TinyID::new("smn", "Latn", "FI") }),
      ("sms", const { TinyID::new("sms", "Latn", "FI") }),
      ("sn", const { TinyID::new("sn", "Latn", "ZW") }),
      ("so", const { TinyID::new("so", "Latn", "SO") }),
      ("so-DJ", const { TinyID::new("so", "Latn", "DJ") }),
      ("so-ET", const { TinyID::new("so", "Latn", "ET") }),
      ("so-KE", const { TinyID::new("so", "Latn", "KE") }),
      ("sq", const { TinyID::new("sq", "Latn", "AL") }),
      ("sq-MK", const { TinyID::new("sq", "Latn", "MK") }),
      ("sq-XK", const { TinyID::new("sq", "Latn", "XK") }),
      ("sr", const { TinyID::new("sr", "Cyrl", "RS") }),
      ("sr-Cyrl", const { TinyID::new("sr", "Cyrl", "RS") }),
      ("sr-Cyrl-BA", const { TinyID::new("sr", "Cyrl", "BA") }),
      ("sr-Cyrl-ME", const { TinyID::new("sr", "Cyrl", "ME") }),
      ("sr-Cyrl-XK", const { TinyID::new("sr", "Cyrl", "XK") }),
      ("sr-Latn", const { TinyID::new("sr", "Latn", "RS") }),
      ("sr-Latn-BA", const { TinyID::new("sr", "Latn", "BA") }),
      ("sr-Latn-ME", const { TinyID::new("sr", "Latn", "ME") }),
      ("sr-Latn-XK", const { TinyID::new("sr", "Latn", "XK") }),
      ("su", const { TinyID::new("su", "Latn", "ID") }),
      ("su-Latn", const { TinyID::new("su", "Latn", "ID") }),
      ("sv", const { TinyID::new("sv", "Latn", "SE") }),
      ("sv-AX", const { TinyID::new("sv", "Latn", "AX") }),
      ("sv-FI", const { TinyID::new("sv", "Latn", "FI") }),
      ("sw", const { TinyID::new("sw", "Latn", "TZ") }),
      ("sw-CD", const { TinyID::new("sw", "Latn", "CD") }),
      ("sw-KE", const { TinyID::new("sw", "Latn", "KE") }),
      ("sw-UG", const { TinyID::new("sw", "Latn", "UG") }),
      ("ta", const { TinyID::new("ta", "Taml", "IN") }),
      ("ta-LK", const { TinyID::new("ta", "Taml", "LK") }),
      ("ta-MY", const { TinyID::new("ta", "Taml", "MY") }),
      ("ta-SG", const { TinyID::new("ta", "Taml", "SG") }),
      ("te", const { TinyID::new("te", "Telu", "IN") }),
      ("teo", const { TinyID::new("teo", "Latn", "UG") }),
      ("teo-KE", const { TinyID::new("teo", "Latn", "KE") }),
      ("tg", const { TinyID::new("tg", "Cyrl", "TJ") }),
      ("th", const { TinyID::new("th", "Thai", "TH") }),
      ("ti", const { TinyID::new("ti", "Ethi", "ET") }),
      ("ti-ER", const { TinyID::new("ti", "Ethi", "ER") }),
      ("tk", const { TinyID::new("tk", "Latn", "TM") }),
      ("to", const { TinyID::new("to", "Latn", "TO") }),
      ("tok", const { TinyID::new("tok", "Latn", "001") }),
      ("tr", const { TinyID::new("tr", "Latn", "TR") }),
      ("tr-CY", const { TinyID::new("tr", "Latn", "CY") }),
      ("tt", const { TinyID::new("tt", "Cyrl", "RU") }),
      ("twq", const { TinyID::new("twq", "Latn", "NE") }),
      ("tzm", const { TinyID::new("tzm", "Latn", "MA") }),
      ("ug", const { TinyID::new("ug", "Arab", "CN") }),
      ("uk", const { TinyID::new("uk", "Cyrl", "UA") }),
      ("und", const { TinyID::new("und", "Latn", "US") }),
      ("ur", const { TinyID::new("ur", "Arab", "PK") }),
      ("ur-IN", const { TinyID::new("ur", "Arab", "IN") }),
      ("uz", const { TinyID::new("uz", "Latn", "UZ") }),
      ("uz-Arab", const { TinyID::new("uz", "Arab", "AF") }),
      ("uz-Cyrl", const { TinyID::new("uz", "Cyrl", "UZ") }),
      ("uz-Latn", const { TinyID::new("uz", "Latn", "UZ") }),
      ("vai", const { TinyID::new("vai", "Vaii", "LR") }),
      ("vai-Latn", const { TinyID::new("vai", "Latn", "LR") }),
      ("vai-Vaii", const { TinyID::new("vai", "Vaii", "LR") }),
      ("vi", const { TinyID::new("vi", "Latn", "VN") }),
      ("vun", const { TinyID::new("vun", "Latn", "TZ") }),
      ("wae", const { TinyID::new("wae", "Latn", "CH") }),
      ("wo", const { TinyID::new("wo", "Latn", "SN") }),
      ("xh", const { TinyID::new("xh", "Latn", "ZA") }),
      ("xog", const { TinyID::new("xog", "Latn", "UG") }),
      ("yav", const { TinyID::new("yav", "Latn", "CM") }),
      ("yi", const { TinyID::new("yi", "Hebr", "001") }),
      ("yo", const { TinyID::new("yo", "Latn", "NG") }),
      ("yo-BJ", const { TinyID::new("yo", "Latn", "BJ") }),
      ("yrl", const { TinyID::new("yrl", "Latn", "BR") }),
      ("yrl-CO", const { TinyID::new("yrl", "Latn", "CO") }),
      ("yrl-VE", const { TinyID::new("yrl", "Latn", "VE") }),
      ("yue", const { TinyID::new("yue", "Hant", "HK") }),
      ("yue-Hans", const { TinyID::new("yue", "Hans", "CN") }),
      ("yue-Hant", const { TinyID::new("yue", "Hant", "HK") }),
      ("zgh", const { TinyID::new("zgh", "Tfng", "MA") }),
      ("zh", const { TinyID::new("zh", "Hans", "CN") }),
      ("zh-Hans", const { TinyID::new("zh", "Hans", "CN") }),
      ("zh-Hans-HK", const { TinyID::new("zh", "Hans", "HK") }),
      ("zh-Hans-MO", const { TinyID::new("zh", "Hans", "MO") }),
      ("zh-Hans-SG", const { TinyID::new("zh", "Hans", "SG") }),
      ("zh-Hant", const { TinyID::new("zh", "Hant", "TW") }),
      ("zh-Hant-HK", const { TinyID::new("zh", "Hant", "HK") }),
      ("zh-Hant-MO", const { TinyID::new("zh", "Hant", "MO") }),
      ("zh-pinyin", const { TinyID::new("zh", "Latn", "CN") }),
      ("zu", const { TinyID::new("zu", "Latn", "ZA") }),
      ("st", const { TinyID::new("st", "Latn", "ZA") }),
      ("la", const { TinyID::new("la", "Latn", "VA") }),
      ("ny", const { TinyID::new("ny", "Latn", "MW") }),
      ("sm", const { TinyID::new("sm", "Latn", "WS") }),
      ("jw", const { TinyID::new("jw", "Latn", "ID") }),
      ("ht", const { TinyID::new("ht", "Latn", "HT") }),
      ("co", const { TinyID::new("co", "Latn", "FR") }),
      ("tl", const { TinyID::new("tl", "Latn", "PH") }),
      ("iw", const { TinyID::new("iw", "Hebr", "IL") }),
    ],
  }
}
