use super::TinyID;
/// This is a `phf::Map` constant that maps language codes to their
/// corresponding `TinyID` structs.
///
/// MAX means Maximize.
/// For example: en -> en-Latn-US
///
/// The `TinyID` struct is created using the `TinyID::new()` function, which
/// takes three arguments: `language`, `script`, and `region`. These arguments
/// represent the ISO 639-1 language code, ISO 15924 script code, and ISO 3166-1
/// alpha-2 region code for the language respectively.
///
/// ## Examples
///
/// ```
/// let map = lang_id::maps::max::map();
/// let de = &map["de"];
/// assert_eq!(de.language, "de");
/// assert_eq!(de.script, "Latn");
/// assert_eq!(de.region, "DE");
/// ```
///
/// ```
/// let map = lang_id::maps::max::map();
/// let zh = &map["zh"];
/// assert_eq!(zh.language, "zh");
/// assert_eq!(zh.script, "Hans");
/// assert_eq!(zh.region, "CN");
/// ```
pub const fn map<'m>() -> super::PhfTinyidMap<'m> {
  super::phf::OrderedMap {
    key: 12913932095322966823,
    disps: &[
      (0, 91),
      (0, 19),
      (1, 20),
      (0, 83),
      (1, 10),
      (0, 6),
      (1, 0),
      (0, 382),
      (1, 231),
      (0, 257),
      (0, 288),
      (1, 0),
      (0, 1),
      (0, 4),
      (0, 186),
      (0, 1),
      (0, 0),
      (0, 29),
      (0, 65),
      (0, 17),
      (1, 109),
      (0, 183),
      (0, 27),
      (0, 1),
      (0, 87),
      (0, 54),
      (0, 16),
      (0, 37),
      (1, 111),
      (0, 9),
      (0, 228),
      (0, 328),
      (1, 349),
      (1, 0),
      (0, 83),
      (0, 0),
      (0, 362),
      (0, 389),
      (0, 120),
      (0, 398),
      (0, 17),
      (0, 6),
      (2, 30),
      (0, 144),
      (0, 371),
      (0, 50),
      (0, 149),
      (0, 0),
      (0, 67),
      (0, 97),
      (0, 468),
      (0, 3),
      (0, 320),
      (0, 2),
      (0, 178),
      (0, 319),
      (0, 53),
      (0, 105),
      (0, 571),
      (0, 6),
      (0, 2),
      (0, 163),
      (0, 2),
      (0, 30),
      (1, 7),
      (0, 29),
      (0, 217),
      (0, 2),
      (0, 2),
      (8, 100),
      (4, 412),
      (0, 526),
      (0, 32),
      (0, 206),
      (0, 5),
      (0, 54),
      (0, 139),
      (0, 574),
      (0, 282),
      (6, 173),
      (0, 10),
      (0, 375),
      (0, 0),
      (0, 250),
      (0, 193),
      (0, 437),
      (0, 0),
      (0, 151),
      (0, 132),
      (0, 91),
      (7, 344),
      (1, 241),
      (0, 92),
      (0, 457),
      (0, 91),
      (0, 5),
      (2, 522),
      (1, 152),
      (0, 11),
      (2, 75),
      (0, 151),
      (0, 513),
      (2, 151),
      (0, 14),
      (1, 174),
      (0, 44),
      (0, 71),
      (0, 7),
      (6, 25),
      (0, 164),
      (1, 144),
      (8, 249),
      (0, 350),
      (0, 47),
      (0, 13),
      (3, 534),
      (0, 344),
      (26, 107),
      (0, 124),
      (1, 172),
      (6, 363),
    ],
    idxs: &[
      379, 355, 319, 233, 87, 15, 64, 540, 567, 409, 441, 134, 270, 424, 310, 384,
      126, 328, 263, 111, 518, 519, 444, 61, 250, 390, 39, 19, 489, 53, 460, 496,
      163, 9, 172, 450, 104, 447, 599, 252, 498, 299, 367, 109, 17, 57, 71, 422,
      145, 243, 513, 347, 323, 142, 11, 193, 295, 208, 77, 589, 497, 603, 204, 404,
      329, 535, 432, 326, 573, 144, 333, 321, 569, 350, 464, 113, 324, 583, 590,
      308, 197, 443, 183, 67, 272, 485, 241, 503, 211, 331, 50, 336, 46, 38, 588,
      602, 474, 66, 95, 79, 335, 388, 356, 65, 490, 131, 36, 194, 337, 276, 166,
      317, 186, 158, 545, 304, 224, 214, 54, 279, 20, 451, 416, 520, 547, 348, 361,
      338, 171, 161, 261, 550, 368, 405, 320, 269, 75, 529, 215, 411, 28, 478, 395,
      510, 528, 112, 170, 290, 98, 7, 100, 26, 531, 582, 212, 256, 314, 37, 302,
      285, 418, 414, 182, 468, 259, 59, 564, 389, 374, 572, 133, 216, 117, 119, 557,
      16, 452, 21, 148, 394, 234, 29, 594, 162, 598, 202, 580, 187, 138, 284, 370,
      481, 312, 477, 97, 462, 369, 40, 307, 273, 156, 541, 105, 433, 505, 44, 184,
      106, 480, 523, 188, 417, 89, 341, 440, 25, 492, 439, 506, 486, 94, 181, 371,
      438, 527, 293, 153, 311, 574, 22, 124, 467, 191, 141, 128, 377, 223, 226, 385,
      274, 318, 206, 49, 267, 165, 566, 139, 219, 198, 78, 260, 24, 473, 387, 366,
      262, 517, 84, 423, 373, 96, 140, 12, 530, 516, 472, 43, 27, 596, 560, 425, 62,
      402, 159, 533, 137, 174, 102, 47, 509, 407, 291, 479, 249, 391, 556, 192, 349,
      52, 309, 31, 35, 289, 482, 430, 178, 239, 99, 129, 288, 209, 562, 346, 585,
      221, 150, 277, 210, 457, 185, 83, 412, 413, 305, 381, 130, 426, 164, 82, 344,
      157, 69, 502, 76, 294, 32, 297, 118, 396, 167, 415, 584, 23, 401, 199, 434,
      265, 493, 173, 275, 491, 13, 591, 103, 296, 431, 196, 218, 544, 397, 476, 522,
      51, 80, 536, 597, 245, 120, 554, 152, 399, 342, 316, 207, 542, 488, 116, 280,
      268, 343, 248, 592, 427, 458, 383, 543, 429, 515, 283, 257, 364, 264, 42, 41,
      521, 4, 363, 160, 508, 358, 372, 258, 213, 553, 532, 357, 410, 378, 330, 375,
      135, 303, 189, 483, 222, 600, 190, 549, 578, 552, 470, 10, 495, 180, 559, 266,
      546, 251, 334, 8, 499, 237, 380, 538, 107, 203, 475, 421, 73, 298, 306, 238,
      352, 110, 121, 484, 81, 48, 586, 240, 327, 123, 382, 360, 494, 376, 449, 230,
      448, 354, 398, 534, 14, 0, 408, 143, 568, 571, 229, 127, 205, 400, 45, 217,
      220, 579, 403, 313, 231, 456, 577, 232, 136, 539, 292, 581, 74, 453, 524, 177,
      555, 246, 85, 236, 287, 563, 92, 419, 593, 91, 301, 254, 428, 340, 282, 365,
      575, 2, 420, 88, 155, 322, 442, 315, 101, 469, 176, 332, 201, 459, 345, 445,
      601, 242, 108, 147, 93, 5, 122, 58, 386, 115, 200, 353, 561, 487, 300, 228,
      446, 278, 271, 70, 146, 114, 18, 512, 3, 393, 55, 227, 225, 436, 154, 68, 455,
      86, 537, 56, 149, 570, 286, 463, 1, 576, 281, 471, 511, 595, 504, 501, 151,
      132, 435, 325, 551, 60, 525, 514, 437, 565, 244, 454, 63, 587, 548, 461, 30,
      179, 235, 195, 359, 247, 169, 351, 466, 168, 90, 339, 507, 392, 255, 253, 465,
      33, 6, 362, 526, 406, 175, 34, 72, 500, 125, 558,
    ],
    entries: &[
      ("af", const { TinyID::new("af", "Latn", "ZA") }),
      ("af-NA", const { TinyID::new("af", "Latn", "NA") }),
      ("agq", const { TinyID::new("agq", "Latn", "CM") }),
      ("ak", const { TinyID::new("ak", "Latn", "GH") }),
      ("am", const { TinyID::new("am", "Ethi", "ET") }),
      ("ann", const { TinyID::new("ann", "Latn", "NG") }),
      ("ar", const { TinyID::new("ar", "Arab", "EG") }),
      ("ar-AE", const { TinyID::new("ar", "Arab", "AE") }),
      ("ar-BH", const { TinyID::new("ar", "Arab", "BH") }),
      ("ar-DJ", const { TinyID::new("ar", "Arab", "DJ") }),
      ("ar-DZ", const { TinyID::new("ar", "Arab", "DZ") }),
      ("ar-EG", const { TinyID::new("ar", "Arab", "EG") }),
      ("ar-EH", const { TinyID::new("ar", "Arab", "EH") }),
      ("ar-ER", const { TinyID::new("ar", "Arab", "ER") }),
      ("ar-IL", const { TinyID::new("ar", "Arab", "IL") }),
      ("ar-IQ", const { TinyID::new("ar", "Arab", "IQ") }),
      ("ar-JO", const { TinyID::new("ar", "Arab", "JO") }),
      ("ar-KM", const { TinyID::new("ar", "Arab", "KM") }),
      ("ar-KW", const { TinyID::new("ar", "Arab", "KW") }),
      ("ar-LB", const { TinyID::new("ar", "Arab", "LB") }),
      ("ar-LY", const { TinyID::new("ar", "Arab", "LY") }),
      ("ar-MA", const { TinyID::new("ar", "Arab", "MA") }),
      ("ar-MR", const { TinyID::new("ar", "Arab", "MR") }),
      ("ar-OM", const { TinyID::new("ar", "Arab", "OM") }),
      ("ar-PS", const { TinyID::new("ar", "Arab", "PS") }),
      ("ar-QA", const { TinyID::new("ar", "Arab", "QA") }),
      ("ar-SA", const { TinyID::new("ar", "Arab", "SA") }),
      ("ar-SD", const { TinyID::new("ar", "Arab", "SD") }),
      ("ar-SO", const { TinyID::new("ar", "Arab", "SO") }),
      ("ar-SS", const { TinyID::new("ar", "Arab", "SS") }),
      ("ar-SY", const { TinyID::new("ar", "Arab", "SY") }),
      ("ar-TD", const { TinyID::new("ar", "Arab", "TD") }),
      ("ar-TN", const { TinyID::new("ar", "Arab", "TN") }),
      ("ar-YE", const { TinyID::new("ar", "Arab", "YE") }),
      ("as", const { TinyID::new("as", "Beng", "IN") }),
      ("asa", const { TinyID::new("asa", "Latn", "TZ") }),
      ("ast", const { TinyID::new("ast", "Latn", "ES") }),
      ("az", const { TinyID::new("az", "Latn", "AZ") }),
      ("az-Cyrl", const { TinyID::new("az", "Cyrl", "AZ") }),
      ("az-Latn", const { TinyID::new("az", "Latn", "AZ") }),
      ("bal", const { TinyID::new("bal", "Arab", "PK") }),
      ("bas", const { TinyID::new("bas", "Latn", "CM") }),
      ("be", const { TinyID::new("be", "Cyrl", "BY") }),
      ("bem", const { TinyID::new("bem", "Latn", "ZM") }),
      ("bez", const { TinyID::new("bez", "Latn", "TZ") }),
      ("bg", const { TinyID::new("bg", "Cyrl", "BG") }),
      ("bgc", const { TinyID::new("bgc", "Deva", "IN") }),
      ("bho", const { TinyID::new("bho", "Deva", "IN") }),
      ("bm", const { TinyID::new("bm", "Latn", "ML") }),
      ("bn", const { TinyID::new("bn", "Beng", "BD") }),
      ("bn-IN", const { TinyID::new("bn", "Beng", "IN") }),
      ("bo", const { TinyID::new("bo", "Tibt", "CN") }),
      ("bo-IN", const { TinyID::new("bo", "Tibt", "IN") }),
      ("br", const { TinyID::new("br", "Latn", "FR") }),
      ("brx", const { TinyID::new("brx", "Deva", "IN") }),
      ("bs", const { TinyID::new("bs", "Latn", "BA") }),
      ("bs-Cyrl", const { TinyID::new("bs", "Cyrl", "BA") }),
      ("bs-Latn", const { TinyID::new("bs", "Latn", "BA") }),
      ("ca", const { TinyID::new("ca", "Latn", "ES") }),
      ("ca-AD", const { TinyID::new("ca", "Latn", "AD") }),
      ("ca-FR", const { TinyID::new("ca", "Latn", "FR") }),
      ("ca-IT", const { TinyID::new("ca", "Latn", "IT") }),
      ("ccp", const { TinyID::new("ccp", "Cakm", "BD") }),
      ("ccp-IN", const { TinyID::new("ccp", "Cakm", "IN") }),
      ("ce", const { TinyID::new("ce", "Cyrl", "RU") }),
      ("ceb", const { TinyID::new("ceb", "Latn", "PH") }),
      ("cgg", const { TinyID::new("cgg", "Latn", "UG") }),
      ("chr", const { TinyID::new("chr", "Cher", "US") }),
      ("ckb", const { TinyID::new("ckb", "Arab", "IQ") }),
      ("ckb-IR", const { TinyID::new("ckb", "Arab", "IR") }),
      ("cs", const { TinyID::new("cs", "Latn", "CZ") }),
      ("cv", const { TinyID::new("cv", "Cyrl", "RU") }),
      ("cy", const { TinyID::new("cy", "Latn", "GB") }),
      ("da", const { TinyID::new("da", "Latn", "DK") }),
      ("da-GL", const { TinyID::new("da", "Latn", "GL") }),
      ("dav", const { TinyID::new("dav", "Latn", "KE") }),
      ("de", const { TinyID::new("de", "Latn", "DE") }),
      ("de-AT", const { TinyID::new("de", "Latn", "AT") }),
      ("de-BE", const { TinyID::new("de", "Latn", "BE") }),
      ("de-CH", const { TinyID::new("de", "Latn", "CH") }),
      ("de-IT", const { TinyID::new("de", "Latn", "IT") }),
      ("de-LI", const { TinyID::new("de", "Latn", "LI") }),
      ("de-LU", const { TinyID::new("de", "Latn", "LU") }),
      ("dje", const { TinyID::new("dje", "Latn", "NE") }),
      ("doi", const { TinyID::new("doi", "Deva", "IN") }),
      ("dsb", const { TinyID::new("dsb", "Latn", "DE") }),
      ("dua", const { TinyID::new("dua", "Latn", "CM") }),
      ("dyo", const { TinyID::new("dyo", "Latn", "SN") }),
      ("dz", const { TinyID::new("dz", "Tibt", "BT") }),
      ("ebu", const { TinyID::new("ebu", "Latn", "KE") }),
      ("ee", const { TinyID::new("ee", "Latn", "GH") }),
      ("ee-TG", const { TinyID::new("ee", "Latn", "TG") }),
      ("el", const { TinyID::new("el", "Grek", "GR") }),
      ("el-CY", const { TinyID::new("el", "Grek", "CY") }),
      ("en", const { TinyID::new("en", "Latn", "US") }),
      ("en-001", const { TinyID::new("en", "Latn", "001") }),
      ("en-150", const { TinyID::new("en", "Latn", "150") }),
      ("en-AE", const { TinyID::new("en", "Latn", "AE") }),
      ("en-AG", const { TinyID::new("en", "Latn", "AG") }),
      ("en-AI", const { TinyID::new("en", "Latn", "AI") }),
      ("en-AS", const { TinyID::new("en", "Latn", "AS") }),
      ("en-AT", const { TinyID::new("en", "Latn", "AT") }),
      ("en-AU", const { TinyID::new("en", "Latn", "AU") }),
      ("en-BB", const { TinyID::new("en", "Latn", "BB") }),
      ("en-BE", const { TinyID::new("en", "Latn", "BE") }),
      ("en-BI", const { TinyID::new("en", "Latn", "BI") }),
      ("en-BM", const { TinyID::new("en", "Latn", "BM") }),
      ("en-BS", const { TinyID::new("en", "Latn", "BS") }),
      ("en-BW", const { TinyID::new("en", "Latn", "BW") }),
      ("en-BZ", const { TinyID::new("en", "Latn", "BZ") }),
      ("en-CA", const { TinyID::new("en", "Latn", "CA") }),
      ("en-CC", const { TinyID::new("en", "Latn", "CC") }),
      ("en-CH", const { TinyID::new("en", "Latn", "CH") }),
      ("en-CK", const { TinyID::new("en", "Latn", "CK") }),
      ("en-CM", const { TinyID::new("en", "Latn", "CM") }),
      ("en-CX", const { TinyID::new("en", "Latn", "CX") }),
      ("en-CY", const { TinyID::new("en", "Latn", "CY") }),
      ("en-DE", const { TinyID::new("en", "Latn", "DE") }),
      ("en-DG", const { TinyID::new("en", "Latn", "DG") }),
      ("en-DK", const { TinyID::new("en", "Latn", "DK") }),
      ("en-DM", const { TinyID::new("en", "Latn", "DM") }),
      ("en-ER", const { TinyID::new("en", "Latn", "ER") }),
      ("en-FI", const { TinyID::new("en", "Latn", "FI") }),
      ("en-FJ", const { TinyID::new("en", "Latn", "FJ") }),
      ("en-FK", const { TinyID::new("en", "Latn", "FK") }),
      ("en-FM", const { TinyID::new("en", "Latn", "FM") }),
      ("en-GB", const { TinyID::new("en", "Latn", "GB") }),
      ("en-GD", const { TinyID::new("en", "Latn", "GD") }),
      ("en-GG", const { TinyID::new("en", "Latn", "GG") }),
      ("en-GH", const { TinyID::new("en", "Latn", "GH") }),
      ("en-GI", const { TinyID::new("en", "Latn", "GI") }),
      ("en-GM", const { TinyID::new("en", "Latn", "GM") }),
      ("en-GU", const { TinyID::new("en", "Latn", "GU") }),
      ("en-GY", const { TinyID::new("en", "Latn", "GY") }),
      ("en-HK", const { TinyID::new("en", "Latn", "HK") }),
      ("en-IE", const { TinyID::new("en", "Latn", "IE") }),
      ("en-IL", const { TinyID::new("en", "Latn", "IL") }),
      ("en-IM", const { TinyID::new("en", "Latn", "IM") }),
      ("en-IN", const { TinyID::new("en", "Latn", "IN") }),
      ("en-IO", const { TinyID::new("en", "Latn", "IO") }),
      ("en-JE", const { TinyID::new("en", "Latn", "JE") }),
      ("en-JM", const { TinyID::new("en", "Latn", "JM") }),
      ("en-KE", const { TinyID::new("en", "Latn", "KE") }),
      ("en-KI", const { TinyID::new("en", "Latn", "KI") }),
      ("en-KN", const { TinyID::new("en", "Latn", "KN") }),
      ("en-KY", const { TinyID::new("en", "Latn", "KY") }),
      ("en-LC", const { TinyID::new("en", "Latn", "LC") }),
      ("en-LR", const { TinyID::new("en", "Latn", "LR") }),
      ("en-LS", const { TinyID::new("en", "Latn", "LS") }),
      ("en-MG", const { TinyID::new("en", "Latn", "MG") }),
      ("en-MH", const { TinyID::new("en", "Latn", "MH") }),
      ("en-MO", const { TinyID::new("en", "Latn", "MO") }),
      ("en-MP", const { TinyID::new("en", "Latn", "MP") }),
      ("en-MS", const { TinyID::new("en", "Latn", "MS") }),
      ("en-MT", const { TinyID::new("en", "Latn", "MT") }),
      ("en-MU", const { TinyID::new("en", "Latn", "MU") }),
      ("en-MV", const { TinyID::new("en", "Latn", "MV") }),
      ("en-MW", const { TinyID::new("en", "Latn", "MW") }),
      ("en-MY", const { TinyID::new("en", "Latn", "MY") }),
      ("en-NA", const { TinyID::new("en", "Latn", "NA") }),
      ("en-NF", const { TinyID::new("en", "Latn", "NF") }),
      ("en-NG", const { TinyID::new("en", "Latn", "NG") }),
      ("en-NL", const { TinyID::new("en", "Latn", "NL") }),
      ("en-NR", const { TinyID::new("en", "Latn", "NR") }),
      ("en-NU", const { TinyID::new("en", "Latn", "NU") }),
      ("en-NZ", const { TinyID::new("en", "Latn", "NZ") }),
      ("en-PG", const { TinyID::new("en", "Latn", "PG") }),
      ("en-PH", const { TinyID::new("en", "Latn", "PH") }),
      ("en-PK", const { TinyID::new("en", "Latn", "PK") }),
      ("en-PN", const { TinyID::new("en", "Latn", "PN") }),
      ("en-PR", const { TinyID::new("en", "Latn", "PR") }),
      ("en-PW", const { TinyID::new("en", "Latn", "PW") }),
      ("en-RW", const { TinyID::new("en", "Latn", "RW") }),
      ("en-SB", const { TinyID::new("en", "Latn", "SB") }),
      ("en-SC", const { TinyID::new("en", "Latn", "SC") }),
      ("en-SD", const { TinyID::new("en", "Latn", "SD") }),
      ("en-SE", const { TinyID::new("en", "Latn", "SE") }),
      ("en-SG", const { TinyID::new("en", "Latn", "SG") }),
      ("en-SH", const { TinyID::new("en", "Latn", "SH") }),
      ("en-SI", const { TinyID::new("en", "Latn", "SI") }),
      ("en-SL", const { TinyID::new("en", "Latn", "SL") }),
      ("en-SS", const { TinyID::new("en", "Latn", "SS") }),
      ("en-SX", const { TinyID::new("en", "Latn", "SX") }),
      ("en-SZ", const { TinyID::new("en", "Latn", "SZ") }),
      ("en-TC", const { TinyID::new("en", "Latn", "TC") }),
      ("en-TK", const { TinyID::new("en", "Latn", "TK") }),
      ("en-TO", const { TinyID::new("en", "Latn", "TO") }),
      ("en-TT", const { TinyID::new("en", "Latn", "TT") }),
      ("en-TV", const { TinyID::new("en", "Latn", "TV") }),
      ("en-TZ", const { TinyID::new("en", "Latn", "TZ") }),
      ("en-UG", const { TinyID::new("en", "Latn", "UG") }),
      ("en-UM", const { TinyID::new("en", "Latn", "UM") }),
      ("en-US", const { TinyID::new("en", "Latn", "US") }),
      ("en-VC", const { TinyID::new("en", "Latn", "VC") }),
      ("en-VG", const { TinyID::new("en", "Latn", "VG") }),
      ("en-VI", const { TinyID::new("en", "Latn", "VI") }),
      ("en-VU", const { TinyID::new("en", "Latn", "VU") }),
      ("en-WS", const { TinyID::new("en", "Latn", "WS") }),
      ("en-ZA", const { TinyID::new("en", "Latn", "ZA") }),
      ("en-ZM", const { TinyID::new("en", "Latn", "ZM") }),
      ("en-ZW", const { TinyID::new("en", "Latn", "ZW") }),
      ("eo", const { TinyID::new("eo", "Latn", "001") }),
      ("es", const { TinyID::new("es", "Latn", "ES") }),
      ("es-419", const { TinyID::new("es", "Latn", "419") }),
      ("es-AR", const { TinyID::new("es", "Latn", "AR") }),
      ("es-BO", const { TinyID::new("es", "Latn", "BO") }),
      ("es-BR", const { TinyID::new("es", "Latn", "BR") }),
      ("es-BZ", const { TinyID::new("es", "Latn", "BZ") }),
      ("es-CL", const { TinyID::new("es", "Latn", "CL") }),
      ("es-CO", const { TinyID::new("es", "Latn", "CO") }),
      ("es-CR", const { TinyID::new("es", "Latn", "CR") }),
      ("es-CU", const { TinyID::new("es", "Latn", "CU") }),
      ("es-DO", const { TinyID::new("es", "Latn", "DO") }),
      ("es-EA", const { TinyID::new("es", "Latn", "EA") }),
      ("es-EC", const { TinyID::new("es", "Latn", "EC") }),
      ("es-GQ", const { TinyID::new("es", "Latn", "GQ") }),
      ("es-GT", const { TinyID::new("es", "Latn", "GT") }),
      ("es-HN", const { TinyID::new("es", "Latn", "HN") }),
      ("es-IC", const { TinyID::new("es", "Latn", "IC") }),
      ("es-MX", const { TinyID::new("es", "Latn", "MX") }),
      ("es-NI", const { TinyID::new("es", "Latn", "NI") }),
      ("es-PA", const { TinyID::new("es", "Latn", "PA") }),
      ("es-PE", const { TinyID::new("es", "Latn", "PE") }),
      ("es-PH", const { TinyID::new("es", "Latn", "PH") }),
      ("es-PR", const { TinyID::new("es", "Latn", "PR") }),
      ("es-PY", const { TinyID::new("es", "Latn", "PY") }),
      ("es-SV", const { TinyID::new("es", "Latn", "SV") }),
      ("es-US", const { TinyID::new("es", "Latn", "US") }),
      ("es-UY", const { TinyID::new("es", "Latn", "UY") }),
      ("es-VE", const { TinyID::new("es", "Latn", "VE") }),
      ("et", const { TinyID::new("et", "Latn", "EE") }),
      ("eu", const { TinyID::new("eu", "Latn", "ES") }),
      ("ewo", const { TinyID::new("ewo", "Latn", "CM") }),
      ("fa", const { TinyID::new("fa", "Arab", "IR") }),
      ("fa-AF", const { TinyID::new("fa", "Arab", "AF") }),
      ("ff", const { TinyID::new("ff", "Latn", "SN") }),
      ("ff-Adlm", const { TinyID::new("ff", "Adlm", "GN") }),
      ("ff-Adlm-BF", const { TinyID::new("ff", "Adlm", "BF") }),
      ("ff-Adlm-CM", const { TinyID::new("ff", "Adlm", "CM") }),
      ("ff-Adlm-GH", const { TinyID::new("ff", "Adlm", "GH") }),
      ("ff-Adlm-GM", const { TinyID::new("ff", "Adlm", "GM") }),
      ("ff-Adlm-GW", const { TinyID::new("ff", "Adlm", "GW") }),
      ("ff-Adlm-LR", const { TinyID::new("ff", "Adlm", "LR") }),
      ("ff-Adlm-MR", const { TinyID::new("ff", "Adlm", "MR") }),
      ("ff-Adlm-NE", const { TinyID::new("ff", "Adlm", "NE") }),
      ("ff-Adlm-NG", const { TinyID::new("ff", "Adlm", "NG") }),
      ("ff-Adlm-SL", const { TinyID::new("ff", "Adlm", "SL") }),
      ("ff-Adlm-SN", const { TinyID::new("ff", "Adlm", "SN") }),
      ("ff-Latn", const { TinyID::new("ff", "Latn", "SN") }),
      ("ff-Latn-BF", const { TinyID::new("ff", "Latn", "BF") }),
      ("ff-Latn-CM", const { TinyID::new("ff", "Latn", "CM") }),
      ("ff-Latn-GH", const { TinyID::new("ff", "Latn", "GH") }),
      ("ff-Latn-GM", const { TinyID::new("ff", "Latn", "GM") }),
      ("ff-Latn-GN", const { TinyID::new("ff", "Latn", "GN") }),
      ("ff-Latn-GW", const { TinyID::new("ff", "Latn", "GW") }),
      ("ff-Latn-LR", const { TinyID::new("ff", "Latn", "LR") }),
      ("ff-Latn-MR", const { TinyID::new("ff", "Latn", "MR") }),
      ("ff-Latn-NE", const { TinyID::new("ff", "Latn", "NE") }),
      ("ff-Latn-NG", const { TinyID::new("ff", "Latn", "NG") }),
      ("ff-Latn-SL", const { TinyID::new("ff", "Latn", "SL") }),
      ("fi", const { TinyID::new("fi", "Latn", "FI") }),
      ("fil", const { TinyID::new("fil", "Latn", "PH") }),
      ("fo", const { TinyID::new("fo", "Latn", "FO") }),
      ("fo-DK", const { TinyID::new("fo", "Latn", "DK") }),
      ("fr", const { TinyID::new("fr", "Latn", "FR") }),
      ("fr-BE", const { TinyID::new("fr", "Latn", "BE") }),
      ("fr-BF", const { TinyID::new("fr", "Latn", "BF") }),
      ("fr-BI", const { TinyID::new("fr", "Latn", "BI") }),
      ("fr-BJ", const { TinyID::new("fr", "Latn", "BJ") }),
      ("fr-BL", const { TinyID::new("fr", "Latn", "BL") }),
      ("fr-CA", const { TinyID::new("fr", "Latn", "CA") }),
      ("fr-CD", const { TinyID::new("fr", "Latn", "CD") }),
      ("fr-CF", const { TinyID::new("fr", "Latn", "CF") }),
      ("fr-CG", const { TinyID::new("fr", "Latn", "CG") }),
      ("fr-CH", const { TinyID::new("fr", "Latn", "CH") }),
      ("fr-CI", const { TinyID::new("fr", "Latn", "CI") }),
      ("fr-CM", const { TinyID::new("fr", "Latn", "CM") }),
      ("fr-DJ", const { TinyID::new("fr", "Latn", "DJ") }),
      ("fr-DZ", const { TinyID::new("fr", "Latn", "DZ") }),
      ("fr-GA", const { TinyID::new("fr", "Latn", "GA") }),
      ("fr-GF", const { TinyID::new("fr", "Latn", "GF") }),
      ("fr-GN", const { TinyID::new("fr", "Latn", "GN") }),
      ("fr-GP", const { TinyID::new("fr", "Latn", "GP") }),
      ("fr-GQ", const { TinyID::new("fr", "Latn", "GQ") }),
      ("fr-HT", const { TinyID::new("fr", "Latn", "HT") }),
      ("fr-KM", const { TinyID::new("fr", "Latn", "KM") }),
      ("fr-LU", const { TinyID::new("fr", "Latn", "LU") }),
      ("fr-MA", const { TinyID::new("fr", "Latn", "MA") }),
      ("fr-MC", const { TinyID::new("fr", "Latn", "MC") }),
      ("fr-MF", const { TinyID::new("fr", "Latn", "MF") }),
      ("fr-MG", const { TinyID::new("fr", "Latn", "MG") }),
      ("fr-ML", const { TinyID::new("fr", "Latn", "ML") }),
      ("fr-MQ", const { TinyID::new("fr", "Latn", "MQ") }),
      ("fr-MR", const { TinyID::new("fr", "Latn", "MR") }),
      ("fr-MU", const { TinyID::new("fr", "Latn", "MU") }),
      ("fr-NC", const { TinyID::new("fr", "Latn", "NC") }),
      ("fr-NE", const { TinyID::new("fr", "Latn", "NE") }),
      ("fr-PF", const { TinyID::new("fr", "Latn", "PF") }),
      ("fr-PM", const { TinyID::new("fr", "Latn", "PM") }),
      ("fr-RE", const { TinyID::new("fr", "Latn", "RE") }),
      ("fr-RW", const { TinyID::new("fr", "Latn", "RW") }),
      ("fr-SC", const { TinyID::new("fr", "Latn", "SC") }),
      ("fr-SN", const { TinyID::new("fr", "Latn", "SN") }),
      ("fr-SY", const { TinyID::new("fr", "Latn", "SY") }),
      ("fr-TD", const { TinyID::new("fr", "Latn", "TD") }),
      ("fr-TG", const { TinyID::new("fr", "Latn", "TG") }),
      ("fr-TN", const { TinyID::new("fr", "Latn", "TN") }),
      ("fr-VU", const { TinyID::new("fr", "Latn", "VU") }),
      ("fr-WF", const { TinyID::new("fr", "Latn", "WF") }),
      ("fr-YT", const { TinyID::new("fr", "Latn", "YT") }),
      ("frr", const { TinyID::new("frr", "Latn", "DE") }),
      ("fur", const { TinyID::new("fur", "Latn", "IT") }),
      ("fy", const { TinyID::new("fy", "Latn", "NL") }),
      ("ga", const { TinyID::new("ga", "Latn", "IE") }),
      ("ga-GB", const { TinyID::new("ga", "Latn", "GB") }),
      ("gd", const { TinyID::new("gd", "Latn", "GB") }),
      ("gl", const { TinyID::new("gl", "Latn", "ES") }),
      ("gsw", const { TinyID::new("gsw", "Latn", "CH") }),
      ("gsw-FR", const { TinyID::new("gsw", "Latn", "FR") }),
      ("gsw-LI", const { TinyID::new("gsw", "Latn", "LI") }),
      ("gu", const { TinyID::new("gu", "Gujr", "IN") }),
      ("guz", const { TinyID::new("guz", "Latn", "KE") }),
      ("gv", const { TinyID::new("gv", "Latn", "IM") }),
      ("ha", const { TinyID::new("ha", "Latn", "NG") }),
      ("ha-GH", const { TinyID::new("ha", "Latn", "GH") }),
      ("ha-NE", const { TinyID::new("ha", "Latn", "NE") }),
      ("haw", const { TinyID::new("haw", "Latn", "US") }),
      ("he", const { TinyID::new("he", "Hebr", "IL") }),
      ("hi", const { TinyID::new("hi", "Deva", "IN") }),
      ("hi-Latn", const { TinyID::new("hi", "Latn", "IN") }),
      ("hr", const { TinyID::new("hr", "Latn", "HR") }),
      ("hr-BA", const { TinyID::new("hr", "Latn", "BA") }),
      ("hsb", const { TinyID::new("hsb", "Latn", "DE") }),
      ("hu", const { TinyID::new("hu", "Latn", "HU") }),
      ("hy", const { TinyID::new("hy", "Armn", "AM") }),
      ("ia", const { TinyID::new("ia", "Latn", "001") }),
      ("id", const { TinyID::new("id", "Latn", "ID") }),
      ("ig", const { TinyID::new("ig", "Latn", "NG") }),
      ("ii", const { TinyID::new("ii", "Yiii", "CN") }),
      ("is", const { TinyID::new("is", "Latn", "IS") }),
      ("it", const { TinyID::new("it", "Latn", "IT") }),
      ("it-CH", const { TinyID::new("it", "Latn", "CH") }),
      ("it-SM", const { TinyID::new("it", "Latn", "SM") }),
      ("it-VA", const { TinyID::new("it", "Latn", "VA") }),
      ("ja", const { TinyID::new("ja", "Jpan", "JP") }),
      ("ja-romaji", const { TinyID::new("ja", "Latn", "JP") }),
      ("ja-hepburn", const { TinyID::new("ja", "Latn", "JP") }),
      ("jgo", const { TinyID::new("jgo", "Latn", "CM") }),
      ("jmc", const { TinyID::new("jmc", "Latn", "TZ") }),
      ("jv", const { TinyID::new("jv", "Latn", "ID") }),
      ("ka", const { TinyID::new("ka", "Geor", "GE") }),
      ("kab", const { TinyID::new("kab", "Latn", "DZ") }),
      ("kam", const { TinyID::new("kam", "Latn", "KE") }),
      ("kde", const { TinyID::new("kde", "Latn", "TZ") }),
      ("kea", const { TinyID::new("kea", "Latn", "CV") }),
      ("kgp", const { TinyID::new("kgp", "Latn", "BR") }),
      ("khq", const { TinyID::new("khq", "Latn", "ML") }),
      ("ki", const { TinyID::new("ki", "Latn", "KE") }),
      ("kk", const { TinyID::new("kk", "Cyrl", "KZ") }),
      ("kkj", const { TinyID::new("kkj", "Latn", "CM") }),
      ("kl", const { TinyID::new("kl", "Latn", "GL") }),
      ("kln", const { TinyID::new("kln", "Latn", "KE") }),
      ("km", const { TinyID::new("km", "Khmr", "KH") }),
      ("kn", const { TinyID::new("kn", "Knda", "IN") }),
      ("ko", const { TinyID::new("ko", "Kore", "KR") }),
      ("ko-KP", const { TinyID::new("ko", "Kore", "KP") }),
      ("kok", const { TinyID::new("kok", "Deva", "IN") }),
      ("ks", const { TinyID::new("ks", "Arab", "IN") }),
      ("ks-Arab", const { TinyID::new("ks", "Arab", "IN") }),
      ("ks-Deva", const { TinyID::new("ks", "Deva", "IN") }),
      ("ksb", const { TinyID::new("ksb", "Latn", "TZ") }),
      ("ksf", const { TinyID::new("ksf", "Latn", "CM") }),
      ("ksh", const { TinyID::new("ksh", "Latn", "DE") }),
      ("ku", const { TinyID::new("ku", "Latn", "TR") }),
      ("kw", const { TinyID::new("kw", "Latn", "GB") }),
      ("ky", const { TinyID::new("ky", "Cyrl", "KG") }),
      ("lag", const { TinyID::new("lag", "Latn", "TZ") }),
      ("lb", const { TinyID::new("lb", "Latn", "LU") }),
      ("lg", const { TinyID::new("lg", "Latn", "UG") }),
      ("lkt", const { TinyID::new("lkt", "Latn", "US") }),
      ("ln", const { TinyID::new("ln", "Latn", "CD") }),
      ("ln-AO", const { TinyID::new("ln", "Latn", "AO") }),
      ("ln-CF", const { TinyID::new("ln", "Latn", "CF") }),
      ("ln-CG", const { TinyID::new("ln", "Latn", "CG") }),
      ("lo", const { TinyID::new("lo", "Laoo", "LA") }),
      ("lrc", const { TinyID::new("lrc", "Arab", "IR") }),
      ("lrc-IQ", const { TinyID::new("lrc", "Arab", "IQ") }),
      ("lt", const { TinyID::new("lt", "Latn", "LT") }),
      ("lu", const { TinyID::new("lu", "Latn", "CD") }),
      ("luo", const { TinyID::new("luo", "Latn", "KE") }),
      ("luy", const { TinyID::new("luy", "Latn", "KE") }),
      ("lv", const { TinyID::new("lv", "Latn", "LV") }),
      ("lzh", const { TinyID::new("lzh", "Hant", "CN") }),
      ("lzh-CN", const { TinyID::new("lzh", "Hant", "CN") }),
      ("lzh-Hant", const { TinyID::new("lzh", "Hant", "CN") }),
      ("lzh-Hans", const { TinyID::new("lzh", "Hans", "CN") }),
      ("mai", const { TinyID::new("mai", "Deva", "IN") }),
      ("mas", const { TinyID::new("mas", "Latn", "KE") }),
      ("mas-TZ", const { TinyID::new("mas", "Latn", "TZ") }),
      ("mdf", const { TinyID::new("mdf", "Cyrl", "RU") }),
      ("mer", const { TinyID::new("mer", "Latn", "KE") }),
      ("mfe", const { TinyID::new("mfe", "Latn", "MU") }),
      ("mg", const { TinyID::new("mg", "Latn", "MG") }),
      ("mgh", const { TinyID::new("mgh", "Latn", "MZ") }),
      ("mgo", const { TinyID::new("mgo", "Latn", "CM") }),
      ("mi", const { TinyID::new("mi", "Latn", "NZ") }),
      ("mk", const { TinyID::new("mk", "Cyrl", "MK") }),
      ("ml", const { TinyID::new("ml", "Mlym", "IN") }),
      ("mn", const { TinyID::new("mn", "Cyrl", "MN") }),
      ("mni", const { TinyID::new("mni", "Beng", "IN") }),
      ("mni-Beng", const { TinyID::new("mni", "Beng", "IN") }),
      ("mr", const { TinyID::new("mr", "Deva", "IN") }),
      ("ms", const { TinyID::new("ms", "Latn", "MY") }),
      ("ms-BN", const { TinyID::new("ms", "Latn", "BN") }),
      ("ms-ID", const { TinyID::new("ms", "Latn", "ID") }),
      ("ms-SG", const { TinyID::new("ms", "Latn", "SG") }),
      ("mt", const { TinyID::new("mt", "Latn", "MT") }),
      ("mua", const { TinyID::new("mua", "Latn", "CM") }),
      ("my", const { TinyID::new("my", "Mymr", "MM") }),
      ("mzn", const { TinyID::new("mzn", "Arab", "IR") }),
      ("naq", const { TinyID::new("naq", "Latn", "NA") }),
      ("nb", const { TinyID::new("nb", "Latn", "NO") }),
      ("nb-SJ", const { TinyID::new("nb", "Latn", "SJ") }),
      ("nd", const { TinyID::new("nd", "Latn", "ZW") }),
      ("nds", const { TinyID::new("nds", "Latn", "DE") }),
      ("nds-NL", const { TinyID::new("nds", "Latn", "NL") }),
      ("ne", const { TinyID::new("ne", "Deva", "NP") }),
      ("ne-IN", const { TinyID::new("ne", "Deva", "IN") }),
      ("nl", const { TinyID::new("nl", "Latn", "NL") }),
      ("nl-AW", const { TinyID::new("nl", "Latn", "AW") }),
      ("nl-BE", const { TinyID::new("nl", "Latn", "BE") }),
      ("nl-BQ", const { TinyID::new("nl", "Latn", "BQ") }),
      ("nl-CW", const { TinyID::new("nl", "Latn", "CW") }),
      ("nl-SR", const { TinyID::new("nl", "Latn", "SR") }),
      ("nl-SX", const { TinyID::new("nl", "Latn", "SX") }),
      ("nmg", const { TinyID::new("nmg", "Latn", "CM") }),
      ("nn", const { TinyID::new("nn", "Latn", "NO") }),
      ("nnh", const { TinyID::new("nnh", "Latn", "CM") }),
      ("no", const { TinyID::new("no", "Latn", "NO") }),
      ("nus", const { TinyID::new("nus", "Latn", "SS") }),
      ("nyn", const { TinyID::new("nyn", "Latn", "UG") }),
      ("oc", const { TinyID::new("oc", "Latn", "FR") }),
      ("oc-ES", const { TinyID::new("oc", "Latn", "ES") }),
      ("om", const { TinyID::new("om", "Latn", "ET") }),
      ("om-KE", const { TinyID::new("om", "Latn", "KE") }),
      ("or", const { TinyID::new("or", "Orya", "IN") }),
      ("os", const { TinyID::new("os", "Cyrl", "GE") }),
      ("os-RU", const { TinyID::new("os", "Cyrl", "RU") }),
      ("pa", const { TinyID::new("pa", "Guru", "IN") }),
      ("pa-Arab", const { TinyID::new("pa", "Arab", "PK") }),
      ("pa-Guru", const { TinyID::new("pa", "Guru", "IN") }),
      ("pcm", const { TinyID::new("pcm", "Latn", "NG") }),
      ("pis", const { TinyID::new("pis", "Latn", "SB") }),
      ("pl", const { TinyID::new("pl", "Latn", "PL") }),
      ("ps", const { TinyID::new("ps", "Arab", "AF") }),
      ("ps-PK", const { TinyID::new("ps", "Arab", "PK") }),
      ("pt", const { TinyID::new("pt", "Latn", "BR") }),
      ("pt-AO", const { TinyID::new("pt", "Latn", "AO") }),
      ("pt-CH", const { TinyID::new("pt", "Latn", "CH") }),
      ("pt-CV", const { TinyID::new("pt", "Latn", "CV") }),
      ("pt-GQ", const { TinyID::new("pt", "Latn", "GQ") }),
      ("pt-GW", const { TinyID::new("pt", "Latn", "GW") }),
      ("pt-LU", const { TinyID::new("pt", "Latn", "LU") }),
      ("pt-MO", const { TinyID::new("pt", "Latn", "MO") }),
      ("pt-MZ", const { TinyID::new("pt", "Latn", "MZ") }),
      ("pt-PT", const { TinyID::new("pt", "Latn", "PT") }),
      ("pt-ST", const { TinyID::new("pt", "Latn", "ST") }),
      ("pt-TL", const { TinyID::new("pt", "Latn", "TL") }),
      ("qu", const { TinyID::new("qu", "Latn", "PE") }),
      ("qu-BO", const { TinyID::new("qu", "Latn", "BO") }),
      ("qu-EC", const { TinyID::new("qu", "Latn", "EC") }),
      ("raj", const { TinyID::new("raj", "Deva", "IN") }),
      ("rm", const { TinyID::new("rm", "Latn", "CH") }),
      ("rn", const { TinyID::new("rn", "Latn", "BI") }),
      ("ro", const { TinyID::new("ro", "Latn", "RO") }),
      ("ro-MD", const { TinyID::new("ro", "Latn", "MD") }),
      ("rof", const { TinyID::new("rof", "Latn", "TZ") }),
      ("ru", const { TinyID::new("ru", "Cyrl", "RU") }),
      ("ru-BY", const { TinyID::new("ru", "Cyrl", "BY") }),
      ("ru-KG", const { TinyID::new("ru", "Cyrl", "KG") }),
      ("ru-KZ", const { TinyID::new("ru", "Cyrl", "KZ") }),
      ("ru-MD", const { TinyID::new("ru", "Cyrl", "MD") }),
      ("ru-UA", const { TinyID::new("ru", "Cyrl", "UA") }),
      ("rw", const { TinyID::new("rw", "Latn", "RW") }),
      ("rwk", const { TinyID::new("rwk", "Latn", "TZ") }),
      ("sa", const { TinyID::new("sa", "Deva", "IN") }),
      ("sah", const { TinyID::new("sah", "Cyrl", "RU") }),
      ("saq", const { TinyID::new("saq", "Latn", "KE") }),
      ("sat", const { TinyID::new("sat", "Olck", "IN") }),
      ("sat-Olck", const { TinyID::new("sat", "Olck", "IN") }),
      ("sbp", const { TinyID::new("sbp", "Latn", "TZ") }),
      ("sc", const { TinyID::new("sc", "Latn", "IT") }),
      ("sd", const { TinyID::new("sd", "Arab", "PK") }),
      ("sd-Arab", const { TinyID::new("sd", "Arab", "PK") }),
      ("sd-Deva", const { TinyID::new("sd", "Deva", "IN") }),
      ("se", const { TinyID::new("se", "Latn", "NO") }),
      ("se-FI", const { TinyID::new("se", "Latn", "FI") }),
      ("se-SE", const { TinyID::new("se", "Latn", "SE") }),
      ("seh", const { TinyID::new("seh", "Latn", "MZ") }),
      ("ses", const { TinyID::new("ses", "Latn", "ML") }),
      ("sg", const { TinyID::new("sg", "Latn", "CF") }),
      ("shi", const { TinyID::new("shi", "Tfng", "MA") }),
      ("shi-Latn", const { TinyID::new("shi", "Latn", "MA") }),
      ("shi-Tfng", const { TinyID::new("shi", "Tfng", "MA") }),
      ("si", const { TinyID::new("si", "Sinh", "LK") }),
      ("sk", const { TinyID::new("sk", "Latn", "SK") }),
      ("sl", const { TinyID::new("sl", "Latn", "SI") }),
      ("smn", const { TinyID::new("smn", "Latn", "FI") }),
      ("sms", const { TinyID::new("sms", "Latn", "FI") }),
      ("sn", const { TinyID::new("sn", "Latn", "ZW") }),
      ("so", const { TinyID::new("so", "Latn", "SO") }),
      ("so-DJ", const { TinyID::new("so", "Latn", "DJ") }),
      ("so-ET", const { TinyID::new("so", "Latn", "ET") }),
      ("so-KE", const { TinyID::new("so", "Latn", "KE") }),
      ("sq", const { TinyID::new("sq", "Latn", "AL") }),
      ("sq-MK", const { TinyID::new("sq", "Latn", "MK") }),
      ("sq-XK", const { TinyID::new("sq", "Latn", "XK") }),
      ("sr", const { TinyID::new("sr", "Cyrl", "RS") }),
      ("sr-Cyrl", const { TinyID::new("sr", "Cyrl", "RS") }),
      ("sr-Cyrl-BA", const { TinyID::new("sr", "Cyrl", "BA") }),
      ("sr-Cyrl-ME", const { TinyID::new("sr", "Cyrl", "ME") }),
      ("sr-Cyrl-XK", const { TinyID::new("sr", "Cyrl", "XK") }),
      ("sr-Latn", const { TinyID::new("sr", "Latn", "RS") }),
      ("sr-Latn-BA", const { TinyID::new("sr", "Latn", "BA") }),
      ("sr-Latn-ME", const { TinyID::new("sr", "Latn", "ME") }),
      ("sr-Latn-XK", const { TinyID::new("sr", "Latn", "XK") }),
      ("su", const { TinyID::new("su", "Latn", "ID") }),
      ("su-Latn", const { TinyID::new("su", "Latn", "ID") }),
      ("sv", const { TinyID::new("sv", "Latn", "SE") }),
      ("sv-AX", const { TinyID::new("sv", "Latn", "AX") }),
      ("sv-FI", const { TinyID::new("sv", "Latn", "FI") }),
      ("sw", const { TinyID::new("sw", "Latn", "TZ") }),
      ("sw-CD", const { TinyID::new("sw", "Latn", "CD") }),
      ("sw-KE", const { TinyID::new("sw", "Latn", "KE") }),
      ("sw-UG", const { TinyID::new("sw", "Latn", "UG") }),
      ("ta", const { TinyID::new("ta", "Taml", "IN") }),
      ("ta-LK", const { TinyID::new("ta", "Taml", "LK") }),
      ("ta-MY", const { TinyID::new("ta", "Taml", "MY") }),
      ("ta-SG", const { TinyID::new("ta", "Taml", "SG") }),
      ("te", const { TinyID::new("te", "Telu", "IN") }),
      ("teo", const { TinyID::new("teo", "Latn", "UG") }),
      ("teo-KE", const { TinyID::new("teo", "Latn", "KE") }),
      ("tg", const { TinyID::new("tg", "Cyrl", "TJ") }),
      ("th", const { TinyID::new("th", "Thai", "TH") }),
      ("ti", const { TinyID::new("ti", "Ethi", "ET") }),
      ("ti-ER", const { TinyID::new("ti", "Ethi", "ER") }),
      ("tk", const { TinyID::new("tk", "Latn", "TM") }),
      ("to", const { TinyID::new("to", "Latn", "TO") }),
      ("tok", const { TinyID::new("tok", "Latn", "001") }),
      ("tr", const { TinyID::new("tr", "Latn", "TR") }),
      ("tr-CY", const { TinyID::new("tr", "Latn", "CY") }),
      ("tt", const { TinyID::new("tt", "Cyrl", "RU") }),
      ("twq", const { TinyID::new("twq", "Latn", "NE") }),
      ("tzm", const { TinyID::new("tzm", "Latn", "MA") }),
      ("ug", const { TinyID::new("ug", "Arab", "CN") }),
      ("uk", const { TinyID::new("uk", "Cyrl", "UA") }),
      ("und", const { TinyID::new("und", "Latn", "US") }),
      ("ur", const { TinyID::new("ur", "Arab", "PK") }),
      ("ur-IN", const { TinyID::new("ur", "Arab", "IN") }),
      ("uz", const { TinyID::new("uz", "Latn", "UZ") }),
      ("uz-Arab", const { TinyID::new("uz", "Arab", "AF") }),
      ("uz-Cyrl", const { TinyID::new("uz", "Cyrl", "UZ") }),
      ("uz-Latn", const { TinyID::new("uz", "Latn", "UZ") }),
      ("vai", const { TinyID::new("vai", "Vaii", "LR") }),
      ("vai-Latn", const { TinyID::new("vai", "Latn", "LR") }),
      ("vai-Vaii", const { TinyID::new("vai", "Vaii", "LR") }),
      ("vi", const { TinyID::new("vi", "Latn", "VN") }),
      ("vun", const { TinyID::new("vun", "Latn", "TZ") }),
      ("wae", const { TinyID::new("wae", "Latn", "CH") }),
      ("wo", const { TinyID::new("wo", "Latn", "SN") }),
      ("xh", const { TinyID::new("xh", "Latn", "ZA") }),
      ("xog", const { TinyID::new("xog", "Latn", "UG") }),
      ("yav", const { TinyID::new("yav", "Latn", "CM") }),
      ("yi", const { TinyID::new("yi", "Hebr", "001") }),
      ("yo", const { TinyID::new("yo", "Latn", "NG") }),
      ("yo-BJ", const { TinyID::new("yo", "Latn", "BJ") }),
      ("yrl", const { TinyID::new("yrl", "Latn", "BR") }),
      ("yrl-CO", const { TinyID::new("yrl", "Latn", "CO") }),
      ("yrl-VE", const { TinyID::new("yrl", "Latn", "VE") }),
      ("yue", const { TinyID::new("yue", "Hant", "HK") }),
      ("yue-Hans", const { TinyID::new("yue", "Hans", "CN") }),
      ("yue-Hant", const { TinyID::new("yue", "Hant", "HK") }),
      ("zgh", const { TinyID::new("zgh", "Tfng", "MA") }),
      ("zh", const { TinyID::new("zh", "Hans", "CN") }),
      ("zh-CN", const { TinyID::new("zh", "Hans", "CN") }),
      ("zh-Hans", const { TinyID::new("zh", "Hans", "CN") }),
      ("zh-Hans-HK", const { TinyID::new("zh", "Hans", "HK") }),
      ("zh-Hans-MO", const { TinyID::new("zh", "Hans", "MO") }),
      ("zh-Hans-SG", const { TinyID::new("zh", "Hans", "SG") }),
      ("zh-Hant", const { TinyID::new("zh", "Hant", "TW") }),
      ("zh-Hant-HK", const { TinyID::new("zh", "Hant", "HK") }),
      ("zh-Hant-MO", const { TinyID::new("zh", "Hant", "MO") }),
      ("zh-pinyin", const { TinyID::new("zh", "Latn", "CN") }),
      ("zh-Latn", const { TinyID::new("zh", "Latn", "CN") }),
      ("zu", const { TinyID::new("zu", "Latn", "ZA") }),
      ("st", const { TinyID::new("st", "Latn", "ZA") }),
      ("la", const { TinyID::new("la", "Latn", "VA") }),
      ("ny", const { TinyID::new("ny", "Latn", "MW") }),
      ("sm", const { TinyID::new("sm", "Latn", "WS") }),
      ("jw", const { TinyID::new("jw", "Latn", "ID") }),
      ("ht", const { TinyID::new("ht", "Latn", "HT") }),
      ("co", const { TinyID::new("co", "Latn", "FR") }),
      ("tl", const { TinyID::new("tl", "Latn", "PH") }),
      ("iw", const { TinyID::new("iw", "Hebr", "IL") }),
    ],
  }
}
